### ISSUE TITLE
docopt.cpp

### ISSUE THREAD

**Issue by hoxnox** [conan-io/wishlist#10]
[docopt.cpp](https://github.com/docopt/docopt.cpp) - headers only library for argument parsing inspired by Python's docopt

Requires C++11. Known to work with:
- Clang 3.3 and later
- GCC 4.9
- Visual C++ 2015 RC

**Comment by memsharded** [comment]
Actually, I think it is not header only, but it has just one source and has CMakeLists, so it should be easy.
I think I will not generate all the binary packages, as it is only 1 source, I think keeping it source-only will be fine. I'll try to find time this weekend.

**Comment by memsharded** [comment]
Hi!
I have done a first approach to it, it is almost done: https://github.com/memsharded/conan-docopt

But I have a couple of questions, I would need your feedback:

- I am now packaging the "master" version, as there seem not to be releases. But I would prefer to package a specific release/commit/tag, it is important for repeatibility. I see in the CMakeLists.txt that the current is 0.6.1. Is there some recommended commit, tag to "freeze"?
- I am handling both static/shared versions, but in Windows it seems that a "docopt.lib" linkage library is not being generated, is this true? What I would expect in Win for a simultaneous shared/static build would be: "docopt_s.lib"=static library, "docopt.lib"=linkage lib for shared, "docopt.dll"=shared lib. Am I missing something? 

Thanks very much!

**Comment by hoxnox** [comment]
Thanks for a very fast feedback. Sorry for my slow reaction. Right now I have a few free time to play with new projects. I'll deal with conan packaging, and try to prepare PR into docopt.cpp to make it easier for "conanization" =).

**Comment by memsharded** [comment]
No worries! I had almost finished, just with some info about those issues, it will be done. But if you would like to try yourself, perfect! Just let you know that there are two ways to write the recipe, outside the source repo and inside the source repo (e.g. if you are packaging your own sources, and you don't want to maintain a separate project). Looking forward your feedback then, ask for any help you might need. Thank you!

**Comment by hoxnox** [comment]
About external sources... In your examples you uses git to retrieve the source code. But I want to donwload tarball from "release". What is the most cross-platform way to download, configrm checksum and unpack? Does conan has libraries for it? Should I use python's libraries or utilities like curl, wget?

**Comment by memsharded** [comment]
Nop, you have some conan helpers ``tools.download()``, ``tools.unzip()`` (will untargz too), also several helpers to do checksums. Short described in http://docs.conan.io/en/latest/reference/conanfile.html#retrieving-source-code, but maybe check directly the sources: https://github.com/conan-io/conan/blob/develop/conans/tools.py

**Comment by hoxnox** [comment]
That's great. Thanks.

**Comment by danimtb** [comment]
Docopt is now in conan-center!https://bintray.com/conan-community/conan/docopt%3Aconan/0.6.2%3Astable

Repo: https://github.com/conan-community/conan-docopt

Thanks for the suggestion @hoxnox
