### ISSUE TITLE
EASTL

### ISSUE THREAD

**Issue by amzeratul** [conan-io/wishlist#11]
[EASTL](https://github.com/electronicarts/EASTL) - a very popular STL replacement for game development.

As far as I can tell, it doesn't have any external dependencies. It doesn't even seem to require C++11. Works on VC++, Clang and GCC. Uses CMake.

**Comment by memsharded** [comment]
Cool, I have inspected the CMake, and indeed no deps, a very simple build, seems an easy package then. Probably will be done soon.

**Comment by memsharded** [comment]
I have started with this, able to create the package, but while running an example test, I have an issue. It is trying to use a "EABASE/eabase.h" header file that seems not to exist, seems to be part of the consuming app. Or it can be disabled with a define, and provide some macros. So I have a question, what would be the most typical usage of the library? Can you point to any full example that would be nice to check if the library is linked properly? My attempt so far is here: https://github.com/memsharded/conan-eastl/tree/master/test_package

**Comment by SSE4** [comment]
there is a package from bincrafters:
https://github.com/bincrafters/conan-eastl
https://bintray.com/bincrafters/public-conan/eastl%3Abincrafters

**Comment by solvingj** [comment]
Yes, @amzeratul please let us know if you are able to test/verify, but if not, I think this recipe was pretty straightforward, so I think this can be closed.

**Comment by Croydon** [comment]
I have just updated conventions/scripts for this library.
If there is still interested in it:
  * this needs to be updated to the latest available version
  * Windows needs to be fixed 
  * it should be getting included in conan-center

**Comment by Croydon** [comment]
EASTL is now available, thanks to @madebr 

https://github.com/conan-io/conan-center-index/pull/291
