### ISSUE TITLE
Android NDK Installer

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#111]
From request on bincrafters trello

**Comment by lasote** [comment]
I did some work some time ago to package the NDK and another one to create toolchains for android, it probably doesn't work anymore but could be used as an start point:

https://github.com/lasote/conan-android-ndk
https://github.com/lasote/conan-android-toolchain

With those old recipes and the updated docs in docs.conan.io about cross building should be easy to create new packages.

**Comment by SSE4** [comment]
I've created new one https://github.com/bincrafters/conan-android_ndk_installer

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/3004
