### ISSUE TITLE
SQLPP Connectors - odbc, postgres, mysql, stl, sqlite3

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#112]
from bincrafters trello.

**Comment by Croydon** [comment]
Is this a duplicate of #8 ?

**Comment by solvingj** [comment]
Possibly, I was transferring these items from trello before closing the board so that we didn't lose requests.  Actually, i think it probably warrants a separate ticket for each connector once a solid SQLPP11 package is established.  It seems that in #8, it may not be there yet.

**Comment by Croydon** [comment]
We have now sqlpp11 and sqlpp11-connector-sqlite3 in CCI.

I suggest to close this issue and open individual issues in CCI for the connectors desired. Atomic issues are much better
