### ISSUE TITLE
pkg-config installer for use as build_requires

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#113]
Currently, we've had a need to do the following ugly business: 

https://github.com/bincrafters/conan-zmq/blob/testing/4.2.2/conanfile.py#L19

And we're getting errors on some travis builds as a result. 

Would be nice to have this as a build_requires to streamline the process of depending on it.

**Comment by memsharded** [comment]
That is something new I guess. I have a relatively stable package for zmq
(for previous versions) and does not need pkg-config.

**Comment by SSE4** [comment]
https://github.com/bincrafters/conan-pkg-config_installer

**Comment by solvingj** [comment]
looks like a good start. shall we start CI on it?

**Comment by Croydon** [comment]
I think this can be closed. 

We have pkgconf as a drop in replacement and if someone actual needs pkg-config they could open an issue on conan-center-index without any problem. However, until proofed otherwise I would assume that it is not needed

https://conan.io/center/pkgconf/1.7.3/
