### ISSUE TITLE
muparser

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#114]
fast math parser library: https://github.com/beltoforion/muparser

**Comment by roalz** [comment]
I would also add the muparserx "variant":
website: http://beltoforion.de/article.php?a=muparserx
github: https://github.com/beltoforion/muparserx

**Comment by danimtb** [comment]
Sure! I have transferred the project to conan community and will activate the CI soon. Contributions are welcome 😄

**Comment by Croydon** [comment]
Thanks to @SSE4 the muparser recipe seems now pretty good. Can we get it into conan-center?

**Comment by SSE4** [comment]
@danimtb do you think if your recipe is good enough to be included into conan-centre now?

**Comment by Croydon** [comment]
@roalz I have created a separate issue for muparserx: #201

**Comment by danimtb** [comment]
@SSE4 yeah, it will need some cosmetic changes but it could be easily promoted. We will need to create the branches and update the bintray info

**Comment by Croydon** [comment]
I believe @SSE4 has made an inclusion request in the meantime 😄

**Comment by SSE4** [comment]
@Croydon @danimtb  indeed, already submitted

**Comment by SSE4** [comment]
already in conan-centre
