### ISSUE TITLE
Google RE2 - Regular Expression library

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#119]
It's got a nice Cmakelists file, seems like a no brainer.  
https://github.com/google/re2

**Comment by danimtb** [comment]
As commented by @solvingj in #204:

> used by google effcee project (#205 )
> 
> https://github.com/google/effcee

**Comment by solvingj** [comment]
i have no recollection of this ticket lol

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/412

**Comment by jgsogo** [comment]
Closing then. Thanks!
