### ISSUE TITLE
OpenSceneGraph - 3D graphics toolkit

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#120]
https://github.com/openscenegraph/OpenSceneGraph

This seems like a very mature C++ project.  It's cross-platforms with a very high-quality cmakelists file, and build on my machine on first try with no special handling.  `git clone`, `cmake ..` , `cmake --build .`

**Comment by Croydon** [comment]
@solvingj Please close in favor of https://github.com/conan-io/conan-center-index/issues/171
