### ISSUE TITLE
Cereal - C++11 Header-only serialization library

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#121]
No dependencies!

https://github.com/USCiLab/cereal

**Comment by memsharded** [comment]
Nice!
Interestingly it has a CEREAL_THREAD_SAFE definition, which could be mapped as an option to conan (then use ``package_id()`` to only generate 1 package. 

Testing depends on boost, which could be a nice exercise of a build_require.

I will suggest @pvicente to try to contribute it first to conan-community then to conan-center.

**Comment by pvicente** [comment]
See [package](https://bintray.com/conan-community/conan/cereal%3Aconan) Inclusion request to conan-center has been triggered.

CC: @solvingj @memsharded

**Comment by memsharded** [comment]
Published to conan-center
