### ISSUE TITLE
Tesseract OCR library

### ISSUE THREAD

**Issue by db4** [conan-io/wishlist#122]
Packaging [Tesseract Open Source OCR Engine](https://github.com/tesseract-ocr/tesseract) would be nice. It depends on [leptonica](https://github.com/bincrafters/conan-leptonica) that has been just packaged by bincrafters.

**Comment by theirix** [comment]
I'll package it when leptonica and its deps will be reviewed and accepted in conan-center – a few weeks I think.

**Comment by theirix** [comment]
Latest stable Tesseract 3.05.01 is packaged for Linux, macOS and Windows.
Conan package is available at https://bintray.com/bincrafters/public-conan/tesseract%3Abincrafters, sources are at https://github.com/bincrafters/conan-tesseract .

Package includes the tesseract library and headers, pkgconfig and cmake config files.

Note that library is built at CI without training support (`with_training` option) which requires a lot of complex libraries not packaged yet: fontconfig #20, cairo #18, pango #17.  When they will be available, we can add training support. You can probably build tesseract with training support at your machine.

**Comment by danimtb** [comment]
Already in conan-center thanks to bincrafters again: https://bintray.com/bincrafters/public-conan/tesseract%3Abincrafters

Enjoy!
