### ISSUE TITLE
fftw

### ISSUE THREAD

**Issue by Rikorose** [conan-io/wishlist#123]
[fftw 3](http://www.fftw.org/) is one of the fastest open source fft libraries.

Unfortunately it does not use cmake, but building is straight forward:
```
./configure
make
make install
```

Supporting all possible configurations may become complicated though ([unix](http://www.fftw.org/fftw3_doc/Installation-on-Unix.html#Installation-on-Unix), [non-unix](http://www.fftw.org/fftw3_doc/Installation-on-non_002dUnix-systems.html#Installation-on-non_002dUnix-systems)).

Here is an approach using a custom CMakeLists.txt: [kbinani/conan-fftw](https://github.com/kbinani/conan-fftw).

**Comment by solvingj** [comment]
I suggest adding a link directly to the library homepage or repository itself to the original request, just make it easier to ensure people look at the correct fftw library.

**Comment by Rikorose** [comment]
Yes, I linked the install instructions from the original website though.

**Comment by SSE4** [comment]
in conan-center https://bintray.com/bincrafters/public-conan/fftw%3Abincrafters
