### ISSUE TITLE
FreeGLUT

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#124]
> A free OpenGL utility toolkit, the open-sourced alternative to the GLUT library.

https://github.com/dcnieho/FreeGLUT

**Comment by memsharded** [comment]
+1 for this. I used it some time ago, and it was quite useful for small programs and utilities.

**Comment by Croydon** [comment]
I have some initial work done here https://github.com/Croydon/conan-freeglut

Contributions are welcome :)

**Comment by Croydon** [comment]
There is also https://github.com/iblis-ms/conan_freeglut/tree/develop

**Comment by Croydon** [comment]
So some noticed to begin with:
  * the project name is freeglut, not glut, please always use the exact upstream name (in lowercase)
  * the correct [SPDX](https://spdx.org/licenses/X11.html) name for the license is X11 not X-Consortium

> conan-glut currently disables packaging PDF files for Windows, what's the level of priority for that?

What PDF files?

> conan-freeglut supports MacOS GLX, but my honest opinion is that most of that ought to be merged upstream.

I'm not understanding this point. You do support something which isn't supported upstream without patching it?

> The bintray upload doesn't seem to be working for me for conan-glut, but perhaps I can "trick" travis or appveyor to take care of that?

I have invited you to my repository, please feel free to work there in an own branch 😄

**Comment by Croydon** [comment]
I copied your linking for Windows and it works fine. So linking works now on Windows and Fedora, but fails on (at least) Ubuntu and macOS. If you could help with this part that would be awesome.

**Comment by Croydon** [comment]
> conan-glut is referring to the GLUT interface, rather than any particular implementation. On the Mac I include and link the GLUT framework and have no need for FreeGLUT or X11/GLX there.

Yes, but we do package a specific implementation. So the correct name is freeglut and we also need to pacakge it for macOS.

> With Mac GLX I guess I'd go talk to FreeGLUT if they'd accept that change, rather than maintain that in the conan scope. It's not something that seems all that valuable in practice, but I have heard some folks like X11/GLX on Mac.

Yes, please sugggest changes upstream instead of patching them around in Conan, with the exception when it's absolutely necessary to get it running in a sophisticated way.

> I'll go ahead and try using conan-freeglut on Linux, getting that working ought not be difficult.

Thank you! I would really appreciate help with the linking issues.

**Comment by nigels-com** [comment]
> > conan-glut is referring to the GLUT interface, rather than any particular implementation. 
> >On the Mac I include and link the GLUT framework and have no need for FreeGLUT or X11/GLX there.
> 
> Yes, but we do package a specific implementation. So the correct name is freeglut and we
> also need to package it for macOS.

From the point of view of building portable applications across these platforms, the GLX/X11/FreeGLUT option would not be my first choice.  XQuartz nowadays is not installed by default, not maintained by Apple, and not a native Mac experience.  So in the conan scheme of things I'd need these apps to migrate from `conanfile.txt` to `conanfile.py` to express the platform-specifics of only using FreeGLUT for Windows and Linux?

The idea of conan-glut is to express the GLUT interface dependency, but leave open-ended the particular implementation based on the platform or other considerations.  (Such as the original GLUT: https://github.com/markkilgard/glut perhaps)

**Comment by ericLemanissier** [comment]
ongoing work on https://github.com/bincrafters/conan-freeglut

**Comment by hanun2999** [comment]
QT5.15 build librecad 2.2.0alpha
https://librecad.zulipchat.com/#narrow/stream/110434-general/topic/trying.20to.20install.20dev.20version.20LIbreCad3.2E0.20issues

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/5238

Thanks @ericLemanissier & everyone!
