### ISSUE TITLE
Refresh of capnproto recipe - Now with Cmake

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#127]
This is a great C++ library which has added cmake support since it was originally packaged: 

https://github.com/capnproto/capnproto

https://github.com/lasote/conan-capnproto/blob/release/0.5.3/conanfile.py

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/1489

**Comment by solvingj** [comment]
you are amazing @Croydon thank you!
