### ISSUE TITLE
Aeron - Efficient reliable UDP unicast, UDP multicast, and IPC message transport.

### ISSUE THREAD

**Issue by helmesjo** [conan-io/wishlist#128]
https://github.com/real-logic/aeron

I'm currently looking into high-performance real-time data streaming, and Aeron (with it's C++ client) popped up. I have no experience with it, but it appears to be highly recommended (3000+ stars)!

For a quick overview, look [here](https://github.com/real-logic/aeron/wiki/Design-Overview).

It's supported on _Mac_, _Linux_ & _Windows_. 

## Building
Building & testing appears to be straight forward:
```
mkdir -p cppbuild/Debug
cd cppbuild/Debug
cmake ../..
# cmake -DBUILD_AERON_DRIVER=ON ../.. # optional
cmake --build . --clean-first
ctest
```

## Dependencies
[C++ API Client](https://github.com/real-logic/aeron#c-build):
> Requirements to build HdrHistogram_c. HdrHistogram requires zlib.h currently. So on Ubuntu:
    `$ sudo apt-get install libz-dev`

[C Media Driver](https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/c/README.md) (if option `BUILD_AERON_DRIVER=ON`):

> Linux Dependencies:
> C Library (for the system built on)
> -lpthread - pthread Library
> -ldl - DL Library
> -lbsd - BSD Library (optional - will use /dev/urandom directly instead of arc4random if not available)
> -luuid - UUID Library (optional - will use pure random Receiver ID if not available)
> -lm - Math Library

**Comment by danimtb** [comment]
Does it have any dependencies?

**Comment by helmesjo** [comment]
I updated the issue, but in short: 

**_C++ API client_** has an indirect dependency on [zlib](https://bintray.com/conan-community/conan/zlib%3Aconan) through [HdrHistogram](https://github.com/HdrHistogram/HdrHistogram). HdrHistogram is automatically added as an [ExternalProject](https://github.com/real-logic/aeron/blob/ab56167dfa2b4ac939ff3c2ffc83a8d4d4208da7/CMakeLists.txt#L69).

**_C Media Driver_** (the "data shuffler", that may or may not run in same process), which is optional (default is implemented in java), has dependencies listed above. It is enabled with `BUILD_AERON_DRIVER=ON`. It currently only supported on linux & mac.

**Comment by danimtb** [comment]
great, thanks!

**Comment by helmesjo** [comment]
Got a working recipe here, including the C Driver as an option: https://github.com/helmesjo/conan-aeron

Builds for Linux, MacOS & Windows.

￼

￼
