### ISSUE TITLE
Box2D - A 2D Physics Engine for Games

### ISSUE THREAD

**Issue by ArekPiekarz** [conan-io/wishlist#129]
https://github.com/erincatto/Box2D

I would like to use this popular game physics library on the following configurations (all 64-bit):
- Windows 10 with GCC 7.3 and Clang 5.0.1, both from Msys2
- the latest Ubuntu (currently 17.10) with its GCC and Clang

Note that the last tagged release v2.3.1 was in 2014, but the library has been updated fairly regularly on Github since that time. Therefore a "latest" package would be welcome.

I have found 2 existing recipes in conan-transit, I haven't yet checked if they still work:
box2d/2.3.1-374664b@lasote/vcpkg
Box2D/2.3.2@RussTheAerialist/test

**Comment by danimtb** [comment]
There is a recipe repo here: https://github.com/hi3c/conan-box2d
Maybe @tru can tell us the status of it

**Comment by danimtb** [comment]
There is ongoing work being done here: https://github.com/conan-community/conan-box2d

Will be soon in conan center

**Comment by solvingj** [comment]
Appears to be in Conan center now, great job @danimtb

**Comment by danimtb** [comment]
Indeed. Thanks for the reminder!
