### ISSUE TITLE
Paho

### ISSUE THREAD

**Issue by uilianries** [conan-io/wishlist#13]
[Paho](https://www.eclipse.org/paho/clients/c/) is library support for MQTT protocol (Internet of Things).

Projects as [Macchina.io](http://macchina.io/), uses this library.

**Comment by danimtb** [comment]
We have now paho-c and paho-cpp libraries available in conan-center and a [conanfile.py](https://github.com/eclipse/paho.mqtt.c/blob/master/conanfile.py) already in mqtt.paho.c official repository.
