### ISSUE TITLE
liquid-dsp/1.3.1 - digital signal processing library for software-defined radios

### ISSUE THREAD

**Issue by mckunda** [conan-io/wishlist#138]
https://github.com/jgaeddert/liquid-dsp/tree/v1.3.1
http://liquidsdr.org/doc/installation/
OS: Windows 7
Compiler: Clang/LLVM
> a free and open-source signal processing library for software-defined radios written in C. Its purpose is to provide a set of extensible DSP modules that do not rely on external dependencies or cumbersome frameworks.

**Comment by Croydon** [comment]
Done by https://github.com/conan-io/conan-center-index/pull/5956
