### ISSUE TITLE
Immer - immutable data structures

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#139]
https://github.com/arximboldi/immer
Cmake, moderate dep complexity (boost coroutine). perfect example of something people might want to experiment with but don’t want the hassle of getting build to work. 800 github stats is significant.

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/3633

**Comment by SSE4** [comment]
yes
