### ISSUE TITLE
Still no popular gui libraries

### ISSUE THREAD

**Issue by KaungZawHtet** [conan-io/wishlist#140]
wxwidgets, gtkmm, dear imgui and so on. Please add those as quick as possible

**Comment by Croydon** [comment]
I believe that atomic wishes are better than epic ones.

Also the huge libs have most often many dependencies themselves. As more small libs are packaged the easier it gets to package eventually the big stuff.

**Comment by KaungZawHtet** [comment]
Awaiting gtkmm

**Comment by Croydon** [comment]
* imgui is in conan-center
  * Qt: #2 
  * wxWidgets: #104 
  * gtkmm: #179 

Please close this in favour of the above.
