### ISSUE TITLE
Apache Thrift - An interface definition language and binary communication protocol

### ISSUE THREAD

**Issue by helmesjo** [conan-io/wishlist#143]
**Repo:** https://github.com/apache/thrift

### About:

> Thrift is an interface definition language and binary communication protocol[1] used for defining and creating services for numerous languages. It forms a remote procedure call (RPC) framework [..]

 -[Wikipedia](https://en.wikipedia.org/wiki/Apache_Thrift)

### Note on dependencies:

> If your C++ environment implements C++11 or later, thrift will automatically use std::shared_ptr. Otherwise you will need the boost library to provide a shared_ptr implementation for C++ environments pre-C++11. [..]

 -[Thrift docs](https://thrift.apache.org/lib/cpp#dependencies)

**Comment by helmesjo** [comment]
I've started working on a recipe that can be found here: [helmesjo/conan-thrift](https://github.com/helmesjo/conan-thrift).
It is based on the [bincrafters conan template](https://github.com/bincrafters/conan-templates).

Currently builds for linux (GCC) & windows (VS17).

**Comment by helmesjo** [comment]
Builds on GCC, Clang, Apple-Clang & Visual Studio (see [here](https://travis-ci.org/helmesjo/conan-thrift). 

At the time of writing there are two missing pre-built packages (flex & bison) which fails two different jobs.

Considering this one done!

**Comment by solvingj** [comment]
Great Job BTW.  Hopefully we'll get the flex and bison working so your badges can all be green :)

**Comment by helmesjo** [comment]
Thanks! :)

**Comment by Croydon** [comment]
@helmesjo Could you please re-open this as it isn't in conan-center right now?

Would you also be interested in bringing it to Bincrafters?

**Comment by helmesjo** [comment]
Done!

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/1700

**Comment by helmesjo** [comment]
@Croydon I guess that package does not include the thrift compiler/executable? So we need to use `thrift_installer/0.13.0@bincrafters/stable` for that?

**Edit**
Actually, the compiler is built (`BUILD_COMPILER=True`), but the bin folder is never added to the envars: `self.env_info.path.append(os.path.join(self.package_folder, "bin"))`

**Comment by uilianries** [comment]
@helmesjo the package in Conan Center Index includes the executable.

**Comment by helmesjo** [comment]
@uilianries Yes, but the bin folder is not appended to the package envars (this is needed for the `virtualenv` generator, allowing `find_program(thrift ...)` in cmake to work automagically).

**Comment by uilianries** [comment]
@helmesjo indeed! I'll open a PR to fix it. Thanks!

**Comment by Croydon** [comment]
Generally speaking, we don't split binaries and libraries anymore. The regular case should be now one package, no separate `xyz_installer` package anymore
