### ISSUE TITLE
aws-sdk-cpp

### ISSUE THREAD

**Issue by ThatEmbeddedGuy** [conan-io/wishlist#145]
https://github.com/aws/aws-sdk-cpp
Looks like that may be easy one, since only cmake needed there.

**Comment by ThatEmbeddedGuy** [comment]
Repo has there, but it seems to be broken :(
https://github.com/kmaragon/conan-aws-sdk-cpp

**Comment by jgsogo** [comment]
There is a fork that looks more updated. I have opened an issue to the first author mentioning the forked one, let's wait for the response: https://github.com/kmaragon/conan-aws-sdk-cpp/issues/1

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/4401
