### ISSUE TITLE
Package Tcl/Tk

### ISSUE THREAD

**Issue by luminitadaraban** [conan-io/wishlist#149]
### Description of Problem, Request, or Question
Can you please package Tcl/Tk?
http://tcl.tk/

### Package Details (Include if Applicable)
* Package Name/Version: **tcl_tk/8.6.8**
* Operating System: **Linux** and **Windows**
* Compiler+version: **gcc-7** and **VS14** and **VS15**

**Comment by Croydon** [comment]
At least Tcl is WIP: https://github.com/bincrafters/conan-tcl

From my understanding Tcl and Tk are two separated packages.

https://github.com/bincrafters/community/issues/503

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/3449
