### ISSUE TITLE
Package LibSodium

### ISSUE THREAD

**Issue by luminitadaraban** [conan-io/wishlist#151]
### Description of Problem, Request, or Question
Can you please package LibSodium?
https://github.com/jedisct1/libsodium

### Package Details (Include if Applicable)
* Package Name/Version: **libsodium/1.0.3** or higher
* Operating System: **Linux** and **Windows**
* Compiler+version: **gcc-7** and **VS14** and **VS15**

**Comment by SSE4** [comment]
there is a package on bincrafters repo: https://github.com/bincrafters/conan-libsodium

**Comment by SSE4** [comment]
now in conan-center https://bintray.com/bincrafters/public-conan/libsodium%3Abincrafters
