### ISSUE TITLE
OpenBLAS

### ISSUE THREAD

**Issue by danimtb** [conan-io/wishlist#158]
Requested in #38

There is ongowing work here: https://github.com/danimtb/conan-openblas

**Comment by SSE4** [comment]
this one is dependency of OpenCV as well

**Comment by solvingj** [comment]
How is this one going?  Any recent updates?  This is needed by Openscenegraph.

**Comment by SSE4** [comment]
@solvingj  I've recently revisited this one, and it is tricky one. the problem it uses fortran, and building it with CMake requires kitware-ninja version (as original ninja version doesn't support fortran, and MSVC generator has other issues with fortran). ninja (with kitware branch) will be in conan center soon, then I will be able to finish OpenBLAS.

**Comment by solvingj** [comment]
Ok, thanks for the great update :)
