### ISSUE TITLE
SDL2_ttf

### ISSUE THREAD

**Issue by BigRedEye** [conan-io/wishlist#159]
https://www.libsdl.org/projects/SDL_ttf/

It is a small wrapper around libfreetype, widely used in SDL2 projects. The library depends only on zlib and libfreetype so it can probably be easily packaged.

**Comment by Croydon** [comment]
https://github.com/lasote/conan-sdl2_ttf

**Comment by Croydon** [comment]
WIP: https://github.com/bincrafters/conan-sdl2_ttf thanks to @elizagamedev

**Comment by Croydon** [comment]
Done by https://github.com/conan-io/conan-center-index/pull/5936
