### ISSUE TITLE
GLib

### ISSUE THREAD

**Issue by computerquip** [conan-io/wishlist#16]
Glib is a cross-platform generic utility library. While it can be used by any application, it's more common affiliation is with GTK+ and Gnome.

Website: https://developer.gnome.org/glib/stable/glib.html
Building Guide: https://developer.gnome.org/glib/stable/glib-building.html

It's extensively dependent on pkg-config and GNU make. It would be great to get it working with Windows/Linux. 
In the same source tree are libraries like GObject which tend to follow Glib everywhere. I'm not sure if I should make a separate issue for this but doubt it, so I won't by default.

**Comment by danimtb** [comment]
Ongoing work can be found here: https://github.com/bincrafters/conan-glib

**Comment by SSE4** [comment]
already in conan center
