### ISSUE TITLE
Premake Installer

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#162]
Premake is a build tool like CMake

Having an installer package would be nice as a build requirement.

https://github.com/premake/premake-core

**Comment by solvingj** [comment]
This is a good idea.  Several people at CPPCon were using CMake, or used it in previous companies.

**Comment by Croydon** [comment]
> Several people at CPPCon were using CMake

I guess you meant premake 😄

**Comment by solvingj** [comment]
haha, yes, premake.

**Comment by Croydon** [comment]
WIP: https://github.com/bincrafters/conan-premake_installer
