### ISSUE TITLE
GStreamer

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#164]
> GStreamer is a library for constructing graphs of media-handling components. The applications it supports range from simple Ogg/Vorbis playback, audio/video streaming to complex audio (mixing) and video (non-linear editing) processing. 

https://gstreamer.freedesktop.org/

**Comment by SSE4** [comment]
https://github.com/bincrafters/conan-gstreamer

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/2303

Thanks @ericLemanissier!
