### ISSUE TITLE
OSGEO/GDAL - Open Source Geospatial Data

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#169]
There's already a recipe done for this.  It would be great if someone could modernize it, apply bincrafters templates to it, and setup CI for it. If it builds, we can move it through the pipeline quickly.

https://github.com/osechet/conan-gdal

**Comment by Croydon** [comment]
I can't find any license information for the recipe.

@osechet Under which license are you publishing the Conan recipe for Gdal? A common license in the Conan community is MIT by the way 😄

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/1023
