### ISSUE TITLE
Pango

### ISSUE THREAD

**Issue by computerquip** [conan-io/wishlist#17]
Pango is a text-rendering engine that focuses on internationalization. It's most known from it's use within GTK+. 

Website: http://www.pango.org/Introduction
Repository: https://github.com/GNOME/pango
Build Guide: https://github.com/GNOME/pango/blob/master/README
Build Guide (specific to Windows): https://github.com/GNOME/pango/blob/master/README.win32

Pango has a very hand-in-hand relationship with Cairo. It's generally expected to always be the backend renderer now adays.

**Comment by rohitsanjay** [comment]
I will be making Conan package for "pango" as a subtask of [Simplify building process by utilizing Conan dependency manager #666](https://github.com/synfig/synfig/issues/666).

**Comment by danimtb** [comment]
@rohitsanjay cool! Let us know how it goes and don't forget to submit it to Conan Center so the community could benefit from Pango as a Conan Package! https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html

**Comment by feliwir** [comment]
Is almost done, just needs updated cairo: https://github.com/feliwir/conan-pango

**Comment by danimtb** [comment]
Great!! @feliwir what version of Cairo do you need for this?

cc/ @croydon @SSE4

**Comment by feliwir** [comment]
@SSE4 and me are currently working on this (see the open PR). The current cairo pango branch is compiled without freetype support, which is a requirement for Pango.

**Comment by danimtb** [comment]
ok, thanks for the heads-up

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/3459

Thanks @ericLemanissier
