### ISSUE TITLE
dav1d - AV1 decoder

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#171]
> dav1d is a new AV1 cross-platform decoder, open-source, and focused on speed and correctness.

https://code.videolan.org/videolan/dav1d
mirror: https://github.com/videolan/dav1d

AV1 is an open codec from the [Alliance For Open Media](https://aomedia.org)

**Comment by feliwir** [comment]
Would be interesting for production ready AV1 decoding with our FFMPEG package

**Comment by Croydon** [comment]
Closing in favour of https://github.com/conan-io/conan-center-index/issues/4364
