### ISSUE TITLE
Thrust

### ISSUE THREAD

**Issue by Minimonium** [conan-io/wishlist#173]
> Thrust is a parallel algorithms library which resembles the C++ Standard Template Library (STL)
> Apache License 2.0
> Header-Only
> Requires System CUDA

https://github.com/thrust/thrust
https://github.com/thrust/thrust/wiki/Quick-Start-Guide

**Comment by Croydon** [comment]
Fixed by https://github.com/conan-io/conan-center-index/pull/1391
