### ISSUE TITLE
MariaDB Connector

### ISSUE THREAD

**Issue by jboalml** [conan-io/wishlist#178]
I would like to request the MariaDB connector (https://github.com/MariaDB/mariadb-connector-c). It is true that we currently have the MySQL connector available (https://github.com/bincrafters/conan-mysql-connector-c) but since it is licensed under GPL, it forces you to GPL all your code too.

Conversely, the MariaDB connector is LGPL, which means that as long as you dynamically link to it, you can preserve your own code licensing.

Thanks in advance, I am just recently starting to use Conan and I really like it! 😃

**Comment by danimtb** [comment]
Thanks for the request @jboalml!

I have found a quite good and working recipe here: https://github.com/StableCoder/mariadb-connector-c

Please give it a try, it should work!
Maybe the user is willing to contribute it to Conan Center  @StableCoder 😄

**Comment by jboalml** [comment]
Thank you @danimtb, it works perfectly! And thanks to @StableCoder too! It agree that it would be great if you could add your recipe to Conan Center.

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/1695

**Comment by SSE4** [comment]
yes
