### ISSUE TITLE
gtkmm

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#179]
# --> https://github.com/conan-io/conan-center-index/issues/7279 <--

___

> gtkmm is the official C++ interface for the popular GUI library GTK+

https://www.gtkmm.org/en/

[Dependencies](https://developer.gnome.org/gtkmm-tutorial/stable/sec-installation-dependencies.html.en):
 * [sigc++-3.0](https://github.com/conan-io/conan-center-index/pull/178) ✔️
 * gtk4 ✔️
 * [glibmm-2.68](https://github.com/conan-io/conan-center-index/issues/3419) ❌
 * cairomm-1.16 ❌
 * pangomm-2.48 ❌
 * pkg-config ✔️
 * glib-2.0 ✔️
 * pango ✔️
 * cairo ✔️
 * gdk-pixbuf-2.0 ✔️
 * graphene-1.0 ✔️

**Comment by NNemec** [comment]
Indeed, I would be highly interested in this as well. I have seen that glib has been packaged (https://github.com/bincrafters/conan-glib), so my hope would be that all the essentials are in place to build up the stack upwards from there. I am considering to start looking into this myself, but I have no experience with conan and no idea what effort might be involved...

**Comment by hbobenicio** [comment]
this is the overview of [gtkmm dependencies](https://developer.gnome.org/gtkmm-tutorial/stable/sec-installation-dependencies.html.en).

**Comment by UniverseHan** [comment]
How is going on?

**Comment by Croydon** [comment]
https://github.com/conan-io/conan-center-index/pull/3410 needs more love

**Comment by alexanderankin** [comment]
@Croydon any links you would recommend to get a better idea of whats to be done/how to help? looks like some `Package requirements (giomm-2.4 >= 2.27.93 pangomm-1.4 >= 2.27.1 gtk+-2.0)` still need to be added?

**Comment by Croydon** [comment]
@alexanderankin Sorry for the late response.

I added the list of dependencies above to give an overview of what dependencies are still missing. We first need to create packages for those dependencies before we can create a gtkmm package.

**Comment by morevnaproject** [comment]
> * sigc++-3.0 :x:

In Conan Center now ^__^ - https://conan.io/center/libsigcpp

**Comment by Croydon** [comment]
Moved here https://github.com/conan-io/conan-center-index/issues/7279
