### ISSUE TITLE
Cairo

### ISSUE THREAD

**Issue by computerquip** [conan-io/wishlist#18]
Cairo is a very fast and low-level 2D graphics library. In Linux, it's commonly used with compositors and also known to be used with Pango (known as PangoCairo). It does, however, work on most platforms that supports many of its various forms outputs. 

Website: https://www.cairographics.org/
Building Guides: https://www.cairographics.org/building/

Note the lack of a building guide for Linux. It's pretty self explanatory, fortunately, with a basic configure and make generally doing all the heavy lifting.

**Comment by cristianadam** [comment]
Here's a CMake build version of Cairo: https://github.com/Mixaill/cmake.cairo

**Comment by Croydon** [comment]
Work in progress: https://github.com/bincrafters/conan-cairo

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/2847
