### ISSUE TITLE
Parallel STL (PSTL)

### ISSUE THREAD

**Issue by uilianries** [conan-io/wishlist#180]
Include PSTL:

https://github.com/intel/parallelstl

**Comment by uilianries** [comment]
https://github.com/conan-community/conan-parallelstl

**Comment by solvingj** [comment]
Since last year, most of bincrafters team and even conan team agreed that all-lower-case package names for OSS packages was preferable long-term.  I suggest lower-casing this one.

**Comment by uilianries** [comment]
Agreed. The only restriction will be when using cmake_find_package I think.

**Comment by solvingj** [comment]
Oh, I had not heard of find_package being a factor, what is the situation there?

**Comment by uilianries** [comment]
It's not a real problem I think. but parallelstl exports ParallelSTLConfig.cmake file and when conan provides that file with cmake_find_package, is uses the package name so it will be parallelstlConfig.cmake.

**Comment by solvingj** [comment]
ok

**Comment by uilianries** [comment]
I'm going to update TBB and after that rename parallelstl

**Comment by uilianries** [comment]
![parallelstl/20181004@conan/stable](https://screenshotscdn.firefoxusercontent.com/images/c762d7be-baf1-452b-8f63-7de62ab79209.png)

**Comment by SSE4** [comment]
now in conan-center
