### ISSUE TITLE
cppnanomsg

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#182]
We do have https://github.com/bincrafters/conan-nanomsg

let's add https://github.com/nanomsg/cppnanomsg which is the C++ binding for the nanomsg library

**Comment by Croydon** [comment]
This isn't work in progress right now :)

**Comment by uilianries** [comment]
Amazing! :clap:

**Comment by solvingj** [comment]
Really great work!

**Comment by Croydon** [comment]
cppnanomsg is now in conan-center https://bintray.com/bincrafters/public-conan/cppnanomsg%3Abincrafters 🎉
