### ISSUE TITLE
cpr: C++ Requests: Curl for People, a spiritual port of Python Requests

### ISSUE THREAD

**Issue by htfy96** [conan-io/wishlist#184]
- Upstream: https://github.com/whoshuu/cpr
- Description: C++ Requests is a simple wrapper around libcurl inspired by the excellent Python Requests project.
- Additional information: It uses `git submodule` to manage dependencies:
  - `libcurl` and `gtest` are already provided
  - Mongoose: https://github.com/conan-io/wishlist/issues/183

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/450
