### ISSUE TITLE
Pixman

### ISSUE THREAD

**Issue by computerquip** [conan-io/wishlist#19]
Pixman is a very low-level pixel manipulation library. It's a dependency of Cairo and apparently the X Server. Is rather generic and can be used on a surplus of platforms. 

Website: http://www.pixman.org/
Building Guide: https://cgit.freedesktop.org/pixman/tree/INSTALL

**Comment by cristianadam** [comment]
Here's a CMake version of Pixman: https://github.com/CMakePorts/cmake.pixman

**Comment by computerquip** [comment]
I saw this and wasn't really sure if it was alright to use. I haven't looked at it in-depth and it seems relatively up to date (at most, a few commits behind). The biggest problem I saw was it isn't synced up to any particular release it seems, making it hard to build certain stable versions.

**Comment by memsharded** [comment]
Maybe it could be tried using the pixman origin, and adding just the cmake. In any case, if it is not intended for Win, just using the ``make`` build could be enough.

**Comment by ericLemanissier** [comment]
this can probably closed, now that https://github.com/conan-io/conan-center-index/pull/681 is merged
