### ISSUE TITLE
Google Abseil

### ISSUE THREAD

**Issue by uilianries** [conan-io/wishlist#193]
https://github.com/abseil/abseil-cpp

**Comment by Croydon** [comment]
WIP: https://github.com/bincrafters/conan-abseil

**Comment by uilianries** [comment]
Bincrafters version is working good, but we will give official support for Google Abseil. Sorry, I didn't explained it.

**Comment by Croydon** [comment]
Cross-referencing: https://github.com/abseil/abseil-cpp/issues/187

**Comment by SSE4** [comment]
@uilianries @Croydon what's the status of it? I see issue mentioned above is closed

**Comment by uilianries** [comment]
I've created the package https://github.com/conan-community/conan-abseil to build the recipe from Abseil project. But our goal is https://github.com/abseil/abseil-cpp/pull/197 That feature will be able to add Conan build support there.

But now we have a problem, there is bincrafters/abseil and conan/abseil

**Comment by SSE4** [comment]
but none of them in conan-center yet, right?

**Comment by uilianries** [comment]
That's right!

Let's decide what we gonna do, or we could publish conan/abseil, or bincrafters/abseil. I think Abseil will take some time until release some CI support.

WDYT @danimtb @Croydon @SSE4 ?

**Comment by solvingj** [comment]
If Conan team is willing to commit to abseil long-term, I think it's safe to start pushing any `bincrafters/abseil` users toward `conan/abseil`, and push that toward conan-center.  Once it's in conan-center, we can easily deprecate `bincrafters` after just a few months.

**Comment by Croydon** [comment]
This issue can be closed in favour of https://github.com/conan-io/conan-center-index/issues/710

**Comment by Croydon** [comment]
Abseil is now in CCI  

https://github.com/conan-io/conan-center-index/pull/801
