### ISSUE TITLE
KhronosGroup - SPIRV-Tools Project

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#206]
https://github.com/KhronosGroup/SPIRV-Tools

https://www.khronos.org/registry/spir-v/

SPIR-V is a binary intermediate language for representing graphical-shader stages and compute kernels for multiple Khronos APIs, including OpenCL, OpenGL, and Vulkan. 

The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.  The project includes an assembler, binary module parser, disassembler, validator, and optimizer for SPIR-V.

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/1349
