### ISSUE TITLE
Dicom Toolkit - An image processing toolkit for medical imaging

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#207]
https://github.com/DCMTK/dcmtk

this is a dependency of openscenegraph. 

It also appears that there are actually ~ 10 separate modules in the toolkit.  Each should be a separate package and then there should be a metapackage requiring all of them.

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/1583
