### ISSUE TITLE
libaom-av1 - AV1 Codec Library

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#210]
https://aomedia.googlesource.com/aom/

**Comment by feliwir** [comment]
Working on an implementation: https://github.com/feliwir/conan-libaom
Not fully working yet, due to some linker errors.

**Comment by Croydon** [comment]
WIP https://github.com/conan-io/conan-center-index/pull/4437

**Comment by Croydon** [comment]
Done. Thanks @theirix!
