### ISSUE TITLE
xkbcommon/0.8.2 keyboard descriptions

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/wishlist#217]
xkbcommon is a library for handling of keyboard descriptions, including loading them from disk, parsing them and handling their state. It's mainly meant for client toolkits, window systems, and other system applications; 

Currently that includes:
1. Wayland
2. kmscon
3. GTK+
4. Qt
5. Clutter
6. KWin
7. and others

It is also used by some XCB applications for proper keyboard support. 

https://xkbcommon.org/
https://github.com/xkbcommon/libxkbcommon

it is built with Meson

**Comment by ericLemanissier** [comment]
work in progress in https://github.com/Bincrafters/conan-xkbcommon

**Comment by danimtb** [comment]
@ericLemanissier even if this is now work in progress we would like to keep this open to track the packaging request from users. I will reopen this and tag it as WIP. Thanks 😄

**Comment by uilianries** [comment]
I doing a new review to submit for Conan Center. @ericLemanissier made a great job btw

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/2157
