### ISSUE TITLE
MySQLClient

### ISSUE THREAD

**Issue by hklabbers** [conan-io/wishlist#22]
I'm using Poco for my c++ development and to use Poco with MySQL the MySQLClient is needed to compile the data MySQL library. I'v taken the first steps to create a conanfile.py. This works for OS X, at least it compiles the MySQLClient. But MySQL is not detecting the client, because it looks for this in other places on my filesystem.

My development environment is OS X and apple-clang 7.3.

This is my conanfile.py:

from conans import ConanFile, CMake
from conans.tools import download, unzip

import os, shutil

class MySQLClientConan(ConanFile):
    name = "MySQLClient"
    version = "6.1.6"
    settings = "os", "compiler", "build_type", "arch"
    url = "https://github.com/hklabbers/conan-mysqlclient.git"
    license = "GPL v2"
    author = "Hans Klabbers (hklabbers@yahoo.com)"
    exports = "CMakeLists.txt"
    generators = "cmake", "txt"

    def source(self):
	tar_file = "mysql-connector-c-%s-src.tar.gz" % self.version
	if self.settings.os == "Linux" or self.settings.os == "Macos":
		download("http://dev.mysql.com/get/Downloads/Connector-C/%s" % tar_file, tar_file)
	else:
		download("http://dev.mysql.com/get/Downloads/Connector-C/")
	unzip(tar_file)
	shutil.move("mysql-connector-c-%s-src" % self.version, "mysqlclient")
	os.unlink(tar_file)
	shutil.move("mysqlclient/CMakeLists.txt", "mysqlclient/CMakeListsOriginal.cmake")
	shutil.move("CMakeLists.txt", "mysqlclient/CMakeLists.txt")

    def build(self):
        cmake = CMake(self.settings)
        self.run("cd mysqlclient && mkdir build && cd build && cmake .. ")
        self.run("cd mysqlclient/build && make")

    def package(self):
        self.copy("*.h", dst="include", src="mysqlclient/include")
        self.copy("*.so", dst="lib", src="mysqlclient/build/lib")
	self.copy("*.dylib", dst="lib", src="mysqlclient/build/libmysql")
        self.copy("*.a", dst="lib", src="mysqlclient/build/lib")

    def package_info(self):
        self.cpp_info.libs = ["MySQLClient"]

**Comment by hklabbers** [comment]
I uploaded the conn-file to github.

https://github.com/hklabbers/conan-mysqlclient.git

**Comment by hklabbers** [comment]
Fixed the issue with loading the dynamic library. So I know now that the mysqlclient library compiles successfully. Still having the issue with the poco libraries.

**Comment by memsharded** [comment]
Excellent! I am working on #8 for windows, so I will try your package too for sqlpp11, maybe I run into the same issue. If not, will check later with poco libraries.

**Comment by memsharded** [comment]
Hi! I am working on it, and so far, I am seeing a few issues:
- It seems that you are replacing the CMakeLists, but I cannot find it in the repository. Have you committed & pushed it? Could you please check?
- There are mixed tabs and spaces in the conanfile, that can produce python errors.
- You are not using the ``CMake`` object to define the input of the build appropriately
- On Win fails, as it is not downloading anything.
I have fixed most, but I am running into build errors, which are weird, it is supposed to build in VS2015Upd2. I can do a PR when I have something working, but I have to stop now, I will continue tomorrow. Thanks!

**Comment by memsharded** [comment]
It turns out that using VS12 it builds, it seems that latest VS is breaking things of MySQL code. Unless you have added some HAVE_STRUCT_TIMESPEC in the patched CMake, or something like that, and that makes it work. Looking forward your feedback.

**Comment by hklabbers** [comment]
Hi,

- I added the CMakeLists to the repository.
- I also replaced tabs with spaces (I'm new to python and didn't know this, so I learned something today - which is good). 
- What do you mean with the third bullet?
- I don't have a windows development environment available, so that's why I had the if statement to detect OS X and linux and decided to get back to getting it to work for windows. Good that you picked this up.

I analysed the behaviour of Poco while building. What happens is that Poco tries to find an installed mysqlclient, but this client is not in the usual places. This client is in the local conan repository, so I think that the Poco build needs to be changed. What do you think?

Thank you very much for your help, it is really appreciated. I like the way we are working together on this.

**Comment by hklabbers** [comment]
Hi,

See my previous comment about building Poco. I've changed the recipe for Poco, to add an dependency when MySQL is needed. I changed this locally on my own computer and exported to the local repository (conan export hklabbers/testing). Now Poco is compiled with MySQL support. Conclusion: I have it working on OS X locally.

When we have it also working on linux and windows, we should ask 'lasote' to take my change and add it to his Poco recipe.Is that the workflow we need to follow?

**Comment by memsharded** [comment]
Hi!
I have been able to make it work in VS, building it with VS12, and linking from VS14. 
The diff would be: https://github.com/hklabbers/conan-mysqlclient/compare/master...memsharded:master

Still premature. Some things I have done:
- Handling shared/static linkage of the package
- Some initial handling (just check errors) of runtime

About the third bullet I was talking about: https://github.com/hklabbers/conan-mysqlclient/compare/master...memsharded:master#diff-2b1d42f71f22b7ea0412d7602dec166fR39 and the next line.

Yes, definitely. The flow would be to improve the package until it is a bit more stable, then submit a PR to poco package with the changes necessary to use it. 

So first, I am going to check with my changes how it behaves in linux and OSX, then do a PR to your repo. Then, I could help you if you want setting up travis & appveyor CI, so they are run when pushing commits to the repo automatically, it is very convenient.

**Comment by hklabbers** [comment]
Hi,

Great work! I looked into the tools for packagers yesterday and how to get this running on travis and appveyor. But I hadn't the time to finish it. Your version looks much better than my version, so I will merge it with my version (probably tomorrow, I'm very busy today). I will keep you posted.

**Comment by hklabbers** [comment]
Hi,

Today I merged your changes into the project (as per your PR). Also the build.py and travis stuff is added. The mysqlclient library compiles on travis for the following configurations:

- gcc 4.8
- gcc 4.9
- gcc 5.2
- gcc 5.3
- xcode 7.3 (apple-clang 7.3)
- xcode 7.1 (apple-clang 7.0)
- xcode 6.4 (apple-clang 6.1)
- xcode 6.2 (apple-clang 6.0) 

gcc 4.6 is giving problems with a 'undefined reference to 'clock_gettime' this is probably to a compatibility issue in/between glibc versions. I don't think it is worth fixing (the fix will be to include the rt library when linking the mysqlclient with version). But this needs to be done only when gcc has version 4.6.

Amazing what we have achieved in just a few days! So the next step will be to get this working in appveyor.

**Comment by hklabbers** [comment]
Hi,

As far as I can see now it is okay. The mysqlclient is compiling on linux, windows and mac os x. I guess now it is time to put the binaries in the conan repository.

Cheers!

**Comment by hklabbers** [comment]
Hi,

Luis' PR has been merged. I'm done for now with this library. Anyone with questions or remarks can contact me and I will respond a.s.a.p.

H.

**Comment by memsharded** [comment]
Good job! Just for reference (I know it is up in the thread, but to ease navigation), the links:
- Github repo: https://github.com/hklabbers/conan-mysqlclient
- Conan package: https://www.conan.io/source/mysqlclient/6.1.6/hklabbers/stable

Cheers!

**Comment by lasote** [comment]
Poco library with support for Mysql is now available (only compiling from source, not Poco binaries available):

To enable mysql support:

**conanfile.txt**

```
[requires]
Poco/1.7.3@lasote/stable

[options]
Poco:enable_data_mysql=True
```

In Windows, remember to use Visual 12 and MT (only supported by Mysql library):

`
 conan install -s compiler="Visual Studio" -s compiler.version=12 -s compiler.runtime="MT" --build missing
`

In Linux/OSx:

`
conan install --build missing
`

Thanks! Great work!

**Comment by markD9** [comment]
I'm getting 

```
ERROR: MySQLClient/6.1.6@hklabbers/stable: Error in config, config_options or configure() method, line 26
        raise Exception("MySQLClient static library will not work with VS versions != 12")
        MySQLClient static library will not work with VS versions != 12
```

any chance of having a VS2015 (VS version 14) one?
