### ISSUE TITLE
simdjson:  Yet Another JSON Parser

### ISSUE THREAD

**Issue by uilianries** [conan-io/wishlist#221]
Why another JSON parser?

simdjson is popular on Github (+5k stars) and it has appeared on Github Trends.

Is it header-only (easy stuff to be packaged)?
No.

https://github.com/lemire/simdjson

**Comment by TkTech** [comment]
@uilianries simdjson does have a single .h/.cpp amalgamation https://github.com/lemire/simdjson/tree/master/singleheader which is easy to package and is used by all the bindings.

**Comment by uilianries** [comment]
@TkTech  Amazing! Thanks for sharing it! I gonna provide this package during this week!
