### ISSUE TITLE
asio/1.13.0

### ISSUE THREAD

**Issue by Amphaal** [conan-io/wishlist#223]
Hi,

A bump to the newest version of Asio would be great, as it fixes a lot of bugs, including a critical bug for websocketpp/0.8.1.

Thanks in advance !

**Comment by Croydon** [comment]
Hi @Amphaal!

This is the wrong place to ask for an update. Please open an respective issue in the issue tracker, which is in this case the one of Bincrafters: https://github.com/bincrafters/community/issues

Please use this wishlist only for new packages

**Comment by danimtb** [comment]
Thanks @Croydon
