### ISSUE TITLE
fswatch

### ISSUE THREAD

**Issue by uilianries** [conan-io/wishlist#227]
https://github.com/emcrisostomo/fswatch

> A cross-platform file change monitor with multiple backends: Apple OS X File System Events, *BSD kqueue, Solaris/Illumos File Events Notification, Linux inotify, Microsoft Windows and a stat()-based backend. http://emcrisostomo.github.io/fswatch

/cc @gringolito

**Comment by uilianries** [comment]
Done: https://github.com/bincrafters/conan-fswatch

https://bintray.com/bincrafters/public-conan/fswatch%3Abincrafters

`conan install fswatch/1.14.0@bincrafters/stable`

Waiting for Conan Center approval.

**Comment by Morwenn** [comment]
As far as I can tell it's already been on Conan Center for a while?

**Comment by danimtb** [comment]
@Morwenn you are right! thanks for the reminder 😄
