### ISSUE TITLE
kfr

### ISSUE THREAD

**Issue by tjwrona1992** [conan-io/wishlist#230]
KFR is a fast, modern C++ DSP framework

It is a header only library with the exception of one static library for the DFT portion. It seems like it would be relatively simple to wrap it into a Conan package, but I am not familiar enough with Conan yet to do it myself.

KFR provides the following tools:

- DFT/FFT
- Convolution
- High quality Sample Rate Conversion (SRC)
- EBU R 128 Loudness
- FIR (Finite Impulse Response) filtering
- IIR (Infnite Impulse Response) filtering
- FIR filter design using window method
- Delay line and fractional delay line
- Biquad filters and Biquad cascades
- Biquad design functions
- Oscillators
- Window functions
- Waveshaper
- Stereo conversion (L/R, M/S)
- Goertzel algorithm
- DC Remover
- Audio file reading/writing
- Fast incremental sine/cosine generation
- Pseudorandom number generator
- Sorting
- Mathematical and statistical functions
- A-, B- and C- weighting
- Template expressions
- SIMD functions
- Runtime CPU dispatching
- All vector lengths are supported
- Ring (Circular) buffer

**Comment by uilianries** [comment]
Done!

https://bintray.com/bincrafters/public-conan/kfr%3Abincrafters
https://github.com/bincrafters/conan-kfr

    conan install -r bincrafters kfr/3.0.9@bincrafters/stable

Waiting for Conan Center inclusion

**Comment by danimtb** [comment]
Included in Conan Center! Thanks
