### ISSUE TITLE
libxslt

### ISSUE THREAD

**Issue by dmn-star-home** [conan-io/wishlist#232]
XSLT support for libxml2 (XML toolkit from the GNOME project)
http://xmlsoft.org/XSLT/
https://github.com/GNOME/libxslt

I found multiple _libxslt_ packages in conan repositories created by different users 
_libxslt/1.1.29@annulen/stable_ at conan-transit or at qtproject.  But conan-transit is deprecated now and the packages not working with new conan versions.

Would be nice to have _libxslt_ at bincrafters  together with _libxml_ (bincrafters/conan-libxml2) to round up the xml processing.

**Comment by annulen** [comment]
I've added new version of package at https://github.com/qtwebkit/conan-libxslt. It's based on Bincrafter's libxml2. It has unresolved issue with mingw though

**Comment by dmn-star-home** [comment]
Good news.  Is icu support hardcoded now?

**Comment by annulen** [comment]
No, but I haven't tested confiuguration with iconv

**Comment by annulen** [comment]
You can try using https://github.com/bincrafters/conan-libxslt, it can be built without ICU

**Comment by dmn-star-home** [comment]
Great job! I tested on MacOS and Android, all working fine. By the way, I found exports_sources = ["FindLibXml2.cmake"] in the conanfile.py. Should it be FindLibxslt.cmake?

Should I close this issue now?

**Comment by Croydon** [comment]
No, please let the issue stay open until we have such a package in conan-center

**Comment by timblechmann** [comment]
just a friendly reminder: it would be great to have support for libexslt in the package, too:
http://xmlsoft.org/XSLT/EXSLT/index.html

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/1558
