### ISSUE TITLE
xmlsec XML Security Library

### ISSUE THREAD

**Issue by dmn-star-home** [conan-io/wishlist#233]
XML Security Library

https://github.com/lsh123/xmlsec

XMLSec library provides C based implementation for major XML Security
standards:

    * XML Signature Syntax and Processing
      https://www.w3.org/TR/xmldsig-core

    * XML Encryption Syntax and Processing
      https://www.w3.org/TR/xmlenc-core/

XMLSec is based on well known LibXML (http://xmlsoft.org), LibXSLT
(http://xmlsoft.org/XSLT) and OpenSSL (https://www.openssl.org) libraries

**Comment by danimtb** [comment]
Thanks for the suggestion! libxml2 is already available in Conan Center. Recipe here: https://github.com/bincrafters/conan-libxml2

I see in the repo of xmlsec that it has appveyor and travis ci configured, so probably it not so hard to build and create the Conan recipe then

**Comment by dmn-star-home** [comment]
Thanks for your quick reply. Do you mean the binary recipe only? I need to be able to build xmlsec from source too and cross-compile for Android/iOS. May be someone can adopt the libxml2 repice for.

**Comment by danimtb** [comment]
No, sorry. I said that libxml2 (dependency of xmlsec) is already in Conan Center so some work is already done :)

As the build on xmlsec looks easy, having an initial recipe should not be very complicated. After that, the recipe cna be polished to add crossbuilding support and so on.

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/1876
