### ISSUE TITLE
CUDA runtime

### ISSUE THREAD

**Issue by Hopobcn** [conan-io/wishlist#235]
I wonder a package could be created to distribute the CUDA runtime.
I saw some references to CUDA in the blog post about OpenCV, then I tried to see how packages use it, but then I saw that [conan-ffmpeg](https://github.com/bincrafters/conan-ffmpeg/blob/testing/4.1/conanfile.py#L316) just disables CUDA for now.

Unfortunately after reading a bit the [EULA](https://docs.nvidia.com/cuda/eula/index.html#nvidia-driver-license) i'm not sure if it's possible.

Any ideas?

**Comment by SSE4** [comment]
probably, for certain libraries, the only way is to use virtual package (which doesn't install anything), but just populate `cpp_info`, as you suggest
but this might be confusing for users, e.g. you install CUDA conan package, then you notice it doesn't work and you have to install things by some other means...

**Comment by Hopobcn** [comment]
In conda-forge repo there was a [similar discussion](https://github.com/conda-forge/staged-recipes/issues/654). Seems that installing the cuda toolkit at _package-install-time_ could be another solution. 
Is it possible to create a package that it is always `out of date` so it has to be build each time it gets installed?

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/4844
