### ISSUE TITLE
Cpp-Taskflow

### ISSUE THREAD

**Issue by clin99** [conan-io/wishlist#236]
Cpp-Taskflow 2.2.0: https://github.com/cpp-taskflow/cpp-taskflow

From the repository:

> A fast C++ header-only library to help you quickly write parallel programs with complex task dependencies.

**Comment by Hopobcn** [comment]
I would like to contribute with this implementation https://github.com/Hopobcn/conan-cpp-taskflow

Current decisions:
* Used header-only template therefore `Cpp-TaskflowConfigVersion.cmake`, `Cpp-TaskflowConfig.cmake` and `Cpp-TaskflowTargets.cmake` are not packaged.
* cpp-taskflow requires C++17 so I decided to encode this requirement with `compiler.cppstd` subsetting:
```python
def configure(self):    
    if not self.settings.compiler.cppstd:
        self.settings.compiler.cppstd = 17
    elif self.settings.compiler.cppstd.value < "17":
        raise ConanInvalidConfiguration("cpp-taskflow requires c++17")
```
* cpp-taskflow requires posix threads in Linux/Mac & win32 threads in windows. I don't know what is the best current approach. Right now I manually add this information to `cpp_info.cxxflags` but its missing windows
```python
def package_info(self):
    if not self.settings.os == "Windows":
        self.cpp_info.cxxflags = ["-pthread"]
```
Help would be welcomed

**Comment by SSE4** [comment]
hi @Hopobcn 
as you already have a working recipe, would you like to try to submit it to the [conan center index](https://github.com/conan-io/conan-center-index)?
thanks

**Comment by Hopobcn** [comment]
I've added a PR https://github.com/conan-io/conan-center-index/pull/431 to add v2.2.0 (finally! :-P)

**Comment by Hopobcn** [comment]
https://github.com/conan-io/conan-center-index/pull/431 has been merged. Maybe we could close this issue.

**Comment by danimtb** [comment]
Sure! Thanks for your contribution!!
