### ISSUE TITLE
libarchive

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/wishlist#243]
Library name: libarchive

Library description: Libarchive is an open-source BSD-licensed C programming library that provides streaming access to a variety of different archive formats, including tar, cpio, pax, Zip, and ISO9660 images. The distribution also includes bsdtar and bsdcpio, full-featured implementations of tar and cpio that use libarchive.

Source repository URL: https://github.com/libarchive/libarchive

Project homepage: https://www.libarchive.org/

**Comment by SSE4** [comment]
already in conan center
