### ISSUE TITLE
LibreSSL

### ISSUE THREAD

**Issue by AlexandreBossard** [conan-io/wishlist#251]
https://github.com/libressl-portable/portable

We have a working recipe that we could propose if someone is interested.
This work on linux/windows/macOS and cross-build for android an iOS.

**Comment by danimtb** [comment]
Thanks for the proposal!

Would you like to contribute it to the new central repository? Take a look at https://github.com/conan-io/conan-center-index

I think this one could be very interesting for the community 👐

**Comment by AlexandreBossard** [comment]
Sure, did not notice the issue!

**Comment by Croydon** [comment]
WIP: https://github.com/conan-io/conan-center-index/pull/197

**Comment by AlexandreBossard** [comment]
I know, @theodelrieu is a collegue and the original author of the recipe. Since he had already access to the beta, I kindly ask him to do it for me :)

**Comment by Croydon** [comment]
Done!
