### ISSUE TITLE
Boost 1.72 is missing

### ISSUE THREAD

**Issue by zamazan4ik** [conan-io/wishlist#255]
Hi!
What is going on with Boost 1.72? It was released in a month ago but in repo we have only Boost 1.71.

**Comment by Croydon** [comment]
There is a pull request waiting so it will be soon merged https://github.com/conan-io/conan-center-index/pull/499

Please open new issues about requesting new versions in the Conan Center Index, thanks!

**Comment by zamazan4ik** [comment]
Oh, sorry. Thank you a lot for the answer. I think I can close it.
