### ISSUE TITLE
gnu-radio

### ISSUE THREAD

**Issue by rl-enjoyer** [conan-io/wishlist#264]
Hello,

It would be nice if we could have a package for gnu radio. 

https://www.gnuradio.org/

**Comment by rl-enjoyer** [comment]
oops. Just noticed this repo is depreciated.

**Comment by uilianries** [comment]
Hello @NolanC33 ! Deprecated is not a problem, you still can add it, we have packages from projects which are abandoned nowadays. If you know about a new maintained fork, which is "officially" supported by the community, is also valid.

**Comment by rl-enjoyer** [comment]
Hi @uilianries , what I meant to say is i didn't know *this* repo is depreciated. I didn't see the depreciation notice in README.md.  GNUradio is still being maintained. I submitted an issue in conan-center here https://github.com/conan-io/conan-center-index/issues/6095

**Comment by uilianries** [comment]
@NolanC33 Thank you!
