### ISSUE TITLE
cppunit

### ISSUE THREAD

**Issue by Coderdreams** [conan-io/wishlist#28]
Hi! I attempted to create a package for this but couldn't make it work:

https://github.com/LesleyLai/cppunit

I have no idea why this conanfile.py never downloads the source, and I don't know how to proceed to make it install the generated objects to conan. TIA!

from conans import ConanFile, ConfigureEnvironment

class CppUnitConan(ConanFile):
    name = "cppunit"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    exports = "*"

```
def source(self):
    self.run("git clone https://github.com/LesleyLai/cppunit.git")

def build(self):
    env = ConfigureEnvironment(self.deps_cpp_info, self.settings)
    self.run("%s ./autogen.sh" % (env.command_line))
    self.run("%s ./configure " % (env.command_line))
    self.run("%s make " % (env.command_line))

def package(self):
    self.copy("*.h", dst="include")
    self.copy("*.lib", dst="lib", src="lib")
    self.copy("*.a", dst="lib", src="lib")

def package_info(self):
    self.cpp_info.libs = ["cppunit"]
```

**Comment by Coderdreams** [comment]
I made this work, you guys let me know if it's OK to upload to your repos:

from conans import ConanFile, ConfigureEnvironment

class CppUnitConan(ConanFile):
    name = "cppunit"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"

    def source(self):
        self.run("git clone https://github.com/LesleyLai/cppunit.git")

    def build(self):
        env = ConfigureEnvironment(self.deps_cpp_info, self.settings)
        self.run("%s cppunit/autogen.sh" % (env.command_line))
        self.run("%s cppunit/configure " % (env.command_line))
        self.run("%s make " % (env.command_line))

    def package(self):
        self.copy("*.h", dst="include", src="cppunit/include")
        self.copy("*.so*", dst="lib", src="src/cppunit/.libs")

    def package_info(self):
        self.cpp_info.libs = ["cppunit"]

**Comment by memsharded** [comment]
Good to know that you were able to make it work! Of course it is fine to upload it to conan.io. Your account on conan.io is for your packages, you are free to upload anything as long as it is shared for free, and of course does not violate third parties rights as licenses. It is not a problem if the package may work only for you, but not for others, as long as it is good for you, it is perfect to upload it to conan.io.

Said that, I'd recommend some things:

- This package recipe itself can be hosted in a github repo. Add the URL of the repo to the Conanfile, and it will be linked in the conan.io, and it will be easier for others to collaborate on the package recipe, submit issues, or add contributions with pull requests.
- Use a specific version. The way you have created the recipe, every time you package it, it might use a different commit, which makes very difficult to track changes, bugs, etc. You can download a specific version from https://sourceforge.net/projects/cppunit/files/cppunit/, or maybe checkout a specific commit from the github repo.
- If the package will not compile in Windows, it is easy for consumers to let them know, creating a ``configure()`` method, that checks if ``self.settings.os=="Windows"`` and raising and ``Exception("Windows not supported")``
- Not sure if you really need cppunit (constraint of your project), or you could use a different framework. I'd recommend Catch (https://github.com/philsquared/Catch), google test (gtest), or Trompeloiel (https://github.com/rollbear/trompeloeil). Consider that the repo is older than two years, and the sourceforge releases are from 2008! That is a red flag for me.

These are just some ideas/recommendations, not really necessary to implement them, as I said, if the package is good for you, it is fine. Let me know if you have any further question. Cheers!

**Comment by Coderdreams** [comment]
Thank you for all the suggestions! I've been looking for a better test system but I couldn't find something with a similar layout to what cppunit offered, so I will investigate on those alternatives.
For the moment anyway I'll refine this package in order to share it with other people and as a learning exercise, and see the feasibility of this being used in Windows. I'll let you know of any results.

**Comment by mintyc** [comment]
I've moved on to catch but have legacy needs for cppunit.
I found the fork at libre office to fix a number of windows visual studio issues in 2013/2015.
Not recommended for new projects as even the more recent work in Apache incubator isn't moving cppunit along. Shame.

**Comment by Coderdreams** [comment]
I've uploaded a conan package here: https://www.conan.io/source/cppunit/0.1/Coderdreams/testing
I don't have experience on Windows so I don't know if it will work there. If anyone wants me to check that one I will need a few pointers.

I didn't found another unit test project that fit what I wanted to do. Not coming from a heavy cpp background I run away from macro heavy, header only projects fast. Maybe I'm just biased.

Maybe we could close this issue now?

**Comment by lasote** [comment]
I see that the recipe uses an autogen.sh and a configure, it wont work on Windows, but it's ok, looks good enough. Let's keep opened this issue and if someone want to improve the recipe can comment on this thread.

The github repository with the recipe is: https://github.com/Coderdreams/conan-cppunit

Thanks!

**Comment by opilar** [comment]
We should close this issue then.

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/2955
