### ISSUE TITLE
Assimp

### ISSUE THREAD

**Issue by ZelimDamian** [conan-io/wishlist#29]
Please help adding https://github.com/assimp/assimp

**Comment by jacmoe** [comment]
There is a Conan package for Assimp here: https://www.conan.io/source/assimp/3.3.1/lasote/vcpkg

**Comment by memsharded** [comment]
Please take into account that this is an automatically created package, for Win only, from vcpkg: http://blog.conan.io/2016/10/17/Using-Vcpkg-ports-as-Conan-packages.html. It will not cover other OSs. Still a complete package recipe for all OSs would be interesting. But please report if you are able to try that one, thanks!

**Comment by jacmoe** [comment]
If you are exclusively using Visual Studio, then VCpkg is a viable option, I guess.
I am using CMake because I can get away with not having to maintain build scripts for a whole host of different toolchains and platforms. And since I am using Linux at the moment, I should probably make a separate package for Assimp using plain CMake, since Assimp is using it to build.

**Comment by tobi-tobsen** [comment]
I hate to be that guy, but @jacmoe any news regarding a "proper" conan package which has both linux / windows libs?

**Comment by jacmoe** [comment]
To be totally honest, I have followed Conan, but I still haven't really dug into actually using Conan just yet, mainly because I haven't had a real need for it - CMake works well for me.

Thanks for nagging! :)

I am actually working on a library that could be used as a Conan testbed at the moment, so perhaps Real Soon Now?

**Comment by jacmoe** [comment]
After reading the docs (which are sparse) and finding that Conan has no community / support channel, and trying to make Conan cooperate, I have put this on my maybe-list. So don't expect anything from me regarding this.

**Comment by memsharded** [comment]
Ey, sorry, did you try to reach us and it was not possible? What did fail? You can ping us on twitter, email, and of course we listen to github issues. Unfortunately we don't have enough time to keep working on the wishlist, but the conan repo issues can be perfectly used for support.

Also, the docs are now featuring > 200 pages (https://media.readthedocs.org/pdf/conanio/latest/conanio.pdf), I wouldn't say that is "sparse" ;). If you think something is missing from the docs, you can also ping us or submit an issue in the docs repository. We always try to help the best we can (just damn that limited resource called "time")

No feedback is stupid, thanks for updating :)

**Comment by jacmoe** [comment]
Dear @memsharded :)
I know (all too well) that being an awesome maintainer is not always the easiest thing in the world.
Yes, I will make sure to help to improve the docs - I should not have said that they were sparse, it's just that for each new user a project gets, new questions are raised.. I will get in touch or/and submit PRs for the docs.

So, if I have Conan usage questions or want general advise, I should open a ticket at the main Conan repository?

**Comment by memsharded** [comment]
Hi @jacmoe,
Sure, it isn't easy, just checked your github, you know it very well :) But IMO it is definitely worth, no worries!
Absolutely, you can post any question in the main conan repo, as well as writing us privately (email or twitter) if want to discuss something sensitive to you. Keep in touch, cheers.

**Comment by jacmoe** [comment]
I created a package here: https://github.com/jacmoe/conan-assimp
Will probably improve it over the next weeks, and test it in Windows (maybe) - perhaps I will even submit the package to the Conan repository.
But feel free to test :)

**Comment by jacmoe** [comment]
I uploaded the package Assimp/3.3.1@jacmoe/testing to Conan.io.

I assume that performing an upload again will update the package?

**Comment by jacmoe** [comment]
@tobi-tobsen Thank you for being that guy 👍

**Comment by tobi-tobsen** [comment]
@jacmoe  thanks for your work!

**Comment by solvingj** [comment]
@ZelimDamian since this is officially on Conan-center, can @lasote close now?
