### ISSUE TITLE
Intel TBB

### ISSUE THREAD

**Issue by rhl-** [conan-io/wishlist#3]
Intels Threading Building Blocks. https://www.threadingbuildingblocks.org/

**Comment by memsharded** [comment]
It happens that this is also a (optional) dependency for OpenCV, so I will try to make a proposal for it, so I can use it also in OpenCV.

**Comment by memsharded** [comment]
This is the repository for it, in case you want to follow: https://github.com/memsharded/conan-tbb

There is an initial package recipe, very preliminary and hardcoded, but I was able to run a package test in MSVC14. Instructions how to run the test in the repository readme.

**Comment by memsharded** [comment]
I have created a package: https://www.conan.io/source/TBB/4.4.4/memsharded/testing
Created some binaries for Win (MSVC, various versions), Linux & OSX too, with Travis and Appveyor (just in case, windows binaries still being created at the moment of writing, might take a while, check status at: https://ci.appveyor.com/project/memsharded/conan-tbb)

Feedback welcome.

**Comment by danimtb** [comment]
Already available in conan-center: https://bintray.com/conan-community/conan/TBB%3Aconan
Enjoy!
