### ISSUE TITLE
log4cplus

### ISSUE THREAD

**Issue by monsdar** [conan-io/wishlist#30]
From the project Readme:  
[log4cplus](https://github.com/log4cplus/log4cplus) is a simple to use C++ logging API providing thread--safe, flexible, and arbitrarily granular control over log management and configuration. It is modeled after the Java log4j API.

**Comment by bjadamson** [comment]
Your probably better off with:
https://conan.io/source/spdlog/0.1/memsharded/testing

**Comment by monsdar** [comment]
I'm aware that there are other logging libraries. log4cplus though is what I already have in use.

**Comment by Kretsch0** [comment]
Hey,

I needed the same package. Check this out : https://www.conan.io/source/log4cplus/1.2.0-RC4/Kretsch0/testing

**Comment by monsdar** [comment]
Awesome, always good working with you :)
