### ISSUE TITLE
ImageMagic 7.0.2-10

### ISSUE THREAD

**Issue by Guitarheroua** [conan-io/wishlist#32]
from http://imagemagick.org/

**Comment by Pixinn** [comment]
+1

**Comment by STJEREM** [comment]
+1

**Comment by Mafii** [comment]
+1

**Comment by CodingSpiderFox** [comment]
+1

**Comment by SverreEplov** [comment]
+1

**Comment by StiventoUser** [comment]
+1

**Comment by IgorRyzhkov** [comment]
+1

**Comment by solvingj** [comment]
I like imagemagick, but for the record, this looks like a very challenging library to package.

**Comment by Croydon** [comment]
WIP https://github.com/bincrafters/conan-imagemagick

**Comment by SSE4** [comment]
now in conan centre: https://bintray.com/bincrafters/public-conan/imagemagick%3Abincrafters
