### ISSUE TITLE
PoDoFo 0.9.4

### ISSUE THREAD

**Issue by Guitarheroua** [conan-io/wishlist#33]
PoDoFo is a library to work with the PDF file format. 
From http://podofo.sourceforge.net/

**Comment by MojaveWastelander** [comment]
I made a [package ](https://conan.io/source/podofo/0.9.4/MojaveWastelander/stable). It works on local windows and Linux VM, but don't work on appveyor and travis. In first case in doesn't run test executable (even if its build succesfully) and in second case it doesn't find some headers even though in log is specified that package is installed.

**Comment by Guitarheroua** [comment]
@MojaveWastelander  Thanks a lot!

**Comment by ericLemanissier** [comment]
ongoing work on https://github.com/conan-io/conan-center-index/pull/3594

**Comment by ericLemanissier** [comment]
this one can be closed now that conan-io/conan-center-index#3594 is merged
