### ISSUE TITLE
Qt/4.8.7 - GUI application framework

### ISSUE THREAD

**Issue by sarthakpati** [conan-io/wishlist#35]
For Windows (VS/2015), Linux (GCC/x) and Mac. 64 and 32 bits, Debug and Release configs.

Thanks.

**Comment by zhitko** [comment]
+1

**Comment by Croydon** [comment]
@sarthakpati Ping

**Comment by sarthakpati** [comment]
Would have liked it in 2016/2017. Closing issue.

**Comment by Croydon** [comment]
Issue for newer Qt versions: #2
