### ISSUE TITLE
spdlog logger

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/wishlist#42]
spdlog/0.11.0
gcc

https://github.com/gabime/spdlog

A fast logging library

**Comment by memsharded** [comment]
Isnt spdlog already in Conan?

**Comment by sourcedelica** [comment]
My bad. I missed it somehow. Thanks.

**Comment by memsharded** [comment]
No problem! I was just wondering if the search was not working or something like that, as the service it is being used for indexing and search in the web sometimes fails. Thanks!

**Comment by sourcedelica** [comment]
It's possible. I had a couple others that I looked for and they were there so I didn't create an issue for them, like TBB and Jsoncpp. But it's also possible that I forgot to check for spdlog :)
