### ISSUE TITLE
mysql-connector-cpp

### ISSUE THREAD

**Issue by markD9** [conan-io/wishlist#43]
It would be great to have this one available: https://github.com/mysql/mysql-connector-cpp

It's a C++ wrapper around the MySQL connectors.

**Comment by lasote** [comment]
Any os/compiler? Have you any experience about supported os's or compilers? 

Thanks

**Comment by mintyc** [comment]
better to use the equivalent compatible one in mariadb as the license is more flexible

**Comment by icehockeystar** [comment]
it's official c++ connector from mysql. I would prefer to use it than some alternatives.

**Comment by lasote** [comment]
@icehockeystar What OS's would you use?

**Comment by icehockeystar** [comment]
@lasote Ubuntu Linux 16.04 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lasote** [comment]
Hi! I've uploaded some packages for Linux/gcc:
https://www.conan.io/source/mysql-connector-cpp/2.0.3/lasote/testing

For gcc versions > 5 is necessary to use the setting ` -s compiler.libcxx="libstdc++11"`, it doesn't link with libstc++ (don't know why yet).

You can see an example of use here: https://github.com/lasote/conan-mysql-connector-cpp/tree/testing/2.0.3/test_package

Any doubt or feedback is welcome! If you need any other configuration or OS support just write.

Use --build missing option in `conan install` command, there is no precompiled binaries available for Boost library and libstdc++11.

**Comment by mintyc** [comment]
I should have said the reason for suggesting mariadb's connector instead was licensing.
Mysql's is GPL so 'infects' your code, whereas mariadbs is lgpl. IANAL

**Comment by icehockeystar** [comment]
hi again @lasote 
thank you for your work. I just tested the dependency and I was able to build it into my code and it run.
Unfortunately, the 2.0.3 version of the connector is purposed only for Mysql Servers as of version 5.7 with some X plugin. I use the Mysql 5.6.x and I think there would be appropriate to use the version 1.1.x of the connector which is available in the branch https://github.com/mysql/mysql-connector-cpp/tree/1.1 Could you please build an artifact for the version too?

**Comment by jboalml** [comment]
I would like to bring the request for MariaDB connector (https://github.com/MariaDB/mariadb-connector-c) back to life after two years. I strongly agree with @mintyc that having a LGPL connector is more suitable for many applications since it does not force you to license your code under GPL (as long as you link it dynamically). Any efforts so far?

**Comment by Croydon** [comment]
At Bincrafters we have https://github.com/bincrafters/conan-mysql-connector-c right now.

@jboalml MariaDB ist not the same so please open a new issue for this.

**Comment by Croydon** [comment]
This should be closed in favour of https://github.com/conan-io/conan-center-index/issues/374
