### ISSUE TITLE
sodium/0.9.0 - Functional Reactive Programming (FRP) library

### ISSUE THREAD

**Issue by Confuset** [conan-io/wishlist#44]
Sodium - Functional Reactive Programming (FRP) library

https://github.com/SodiumFRP/sodium-cxx

I would appreciate libs for windows x86 and x86_64

**Comment by lasote** [comment]
Have you compiled Sodium for Windows? Does it compile? What VS version do you need? Or maybe mingw? The readme talks about UNIX, so I wonder if you are using it in Windows.

Thanks

**Comment by Confuset** [comment]
Sorry for taking so long to respond.

In the meantime I tried to compile it on Win64 VS2015. But it didn't work because it depance on Boost and pthread.h.
Resolving Boost was easy. But pthread.h well...thats a different story. I am wondering why it depance on pthread.h while it could use Boost or even c++14. I will contact the author about it...

If someone has an idea about it..let me know

**Comment by Confuset** [comment]
It's been a while. But in the meantime I created a pull request for sodium-cxx making it compileable on windows by removing pthreads.h dependency, which for accepted.

**Comment by Confuset** [comment]
https://github.com/SodiumFRP/sodium-cxx/pull/7

**Comment by danimtb** [comment]
Seems #151 was a duplicated of this issue but conversation is more updated there. Please follow conversation there as there is ongoing effort to have libsodium in conan-center. Thanks!
