### ISSUE TITLE
x264 

### ISSUE THREAD

**Issue by Hennaldo** [conan-io/wishlist#45]
Hi,

It would be great to have x264 available for VS 2013 (v120) in x86 and x86_64

From: http://www.videolan.org/developers/x264.html

**Comment by SSE4** [comment]
there is recipe from bincrafters:
https://bintray.com/bincrafters/public-conan/libx264%3Abincrafters
https://github.com/bincrafters/conan-libx264

**Comment by SSE4** [comment]
already in conan-centre
