### ISSUE TITLE
libwebp

### ISSUE THREAD

**Issue by annulen** [conan-io/wishlist#46]
There are some official binaries at [1,2] so it may be a good idea for conan package to just download and install them

[1] https://developers.google.com/speed/webp/download
[2] https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html

**Comment by solvingj** [comment]
Hi @annulen , going back through this old list, wanted to let you know we have a cross-platform build-from-source libwebp package now:  https://github.com/bincrafters/conan-libwebp/  

Your feedback is always welcome. 

Will give it some time for people to test it, then submit to conan center.  Might finally be able to close this issue after just over a year :)

**Comment by annulen** [comment]
> license = 'AGPL'

Hmm... what?

**Comment by solvingj** [comment]
@ZaMaZaN4iK @SSE4 can one of you please double check the license in conanfile before we publish? Also update readme at bottom.

**Comment by solvingj** [comment]
I just pushed the fix.  Will be updated in an upcoming build. Thanks for looking!

**Comment by solvingj** [comment]
Hi @annulen .  We'll be submitting this to conan-center soon.  Would you be interested in giving it a fresh review?

https://bintray.com/bincrafters/public-conan/libwebp%3Abincrafters

**Comment by danimtb** [comment]
Already in conan center: https://bintray.com/bincrafters/public-conan/libwebp%3Abincrafters

**Comment by anibali** [comment]
It appears as if the build includes `webp`, `webpdecode`, and `webpdemux`, but `webpmux` is missing.

**Comment by danimtb** [comment]
Hi @anibali,

If you have any enhancement proposal please open an issue in the issue tracker of the library

**Comment by anibali** [comment]
@danimtb The issue tracker for the specific repo is disabled: https://github.com/bincrafters/conan-libwebp/. I'm sorry but I'm finding the structure of these repos a bit confusing.

**Comment by anibali** [comment]
Not sure how I missed that, thanks for your patience. I have created a separate issue: https://github.com/bincrafters/community/issues/463

**Comment by danimtb** [comment]
Dont worry @anibali. We are here to help. Glad your issue was solved and thanks to the @bincrafters community :)
