### ISSUE TITLE
Folly

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/wishlist#49]
https://github.com/facebook/folly

**Comment by ssbanerje** [comment]
+1

**Comment by Facon** [comment]
Facebook added CMake support for Windows, which should help in porting Folly to Conan.

**Comment by Pwera** [comment]
Folly is ready on windows x64 targets :)

**Comment by a-teammate** [comment]
The list of dependencies is really big..
if one would do this the clean way, there wouldn't be any.

**Comment by danimtb** [comment]
Some initial works can be found here: https://github.com/bincrafters/conan-folly

Please test and contribute to the repository! Thanks

**Comment by solvingj** [comment]
Yes we need more help on this one.

**Comment by uilianries** [comment]
Hi all!

Folly is ready!

https://bintray.com/bincrafters/public-conan/folly%3Abincrafters

**Comment by uilianries** [comment]
Available in Conan Center:

https://bintray.com/conan/conan-center?filterByPkgName=folly%3Abincrafters
