### ISSUE TITLE
capnproto

### ISSUE THREAD

**Issue by nathanaeljones** [conan-io/wishlist#5]
capnproto - A very fast cerealization library with backwards compatibility. 

I would like to use this for OS X, Linux, and Windows 10  on x86 and x86_64 architectures.

**Comment by lasote** [comment]
Conan package:
https://www.conan.io/source/capnproto/0.5.3/lasote/stable

Github repository:
http://github.com/lasote/conan-capnproto

Any issue report, please, report in the github repository.
