### ISSUE TITLE
Google Sparsehash

### ISSUE THREAD

**Issue by ssbanerje** [conan-io/wishlist#50]
Would appreciate a Conan recipe for Google's Sparsehash library
```
https://github.com/sparsehash/sparsehash
```

**Comment by Croydon** [comment]
WIP: https://github.com/bincrafters/conan-sparsehash

**Comment by solvingj** [comment]
Also, we should Be aware of the c++ 11 version:

https://github.com/sparsehash/sparsehash-c11

Has cmake support.
