### ISSUE TITLE
Taywee/args

### ISSUE THREAD

**Issue by MikeMitterer** [conan-io/wishlist#51]
A simple header-only C++ argument parser library. Supposed to be flexible and powerful, and attempts to be compatible with the functionality of the Python standard argparse library (though not necessarily the API).

Would be cool: https://github.com/Taywee/args
Thanks!

**Comment by memsharded** [comment]
Hi Mike!

Header-only libs are quite easy, do you want to try to create the package yourself? We would love to help if issues. The command ``$ conan new args/version@mike/testing -i -t`` might do large part of the work.

**Comment by MikeMitterer** [comment]
OK - I'll try it!

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/3233
