### ISSUE TITLE
CGAL/4.9

### ISSUE THREAD

**Issue by skyrpex** [conan-io/wishlist#54]
[CGAL](http://www.cgal.org/) is a software project that provides easy access to efficient and reliable geometric algorithms in the form of a C++ library. CGAL is used in various areas needing geometric computation, such as geographic information systems, computer aided design, molecular biology, medical imaging, computer graphics, and robotics.

**Comment by HunorSzabo** [comment]
We are also waiting to the availability of  this library through conan

**Comment by acgetchell** [comment]
... with bated breath. They're up to CGAL 4.11, which has important breaking changes. Naturally, I'll need to use them, so recent CGAL is important (and very, very finicky especially on AppVeyor.)

So, I'll submit a separate request for that.

**Comment by skyrpex** [comment]
I close this one in favour of https://github.com/conan-io/wishlist/issues/91
