### ISSUE TITLE
grpc

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/wishlist#55]
Google's RPC library

Example recipe: https://www.conan.io/source/grpc/1.0.1/sourcedelica/testing

**Comment by memsharded** [comment]
Good, I am going to share about it, this is an interesting library, maybe you get contributions

**Comment by sourcedelica** [comment]
Good point - I forgot that the url was supposed to be for the recipe repo.  Fixed.

**Comment by memsharded** [comment]
Yes, most people interacting with a package want to interact with the recipe first, not the original source repo. If I want to have it, I add another attribute, like ``source_url`` or the like.

**Comment by sztomi** [comment]
@sourcedelica, I just tried you recipe and it seems that a dependency is missing:

```
/usr/bin/ld: cannot find -lboringssl
```

**Comment by sourcedelica** [comment]
Could you log an issue on https://github.com/sourcedelica/conan-grpc and
we'll sort it out there?

Let me know in this issue whether you get this problem building grpc, or
building your own application that is a user of grpc.

Thanks,


-- Eric

**Comment by aurelienrb** [comment]
Hello,
May be you will find useful the work I did to build and create gRPC packages with various compilers (gcc & clang) on Travis:
https://github.com/aurelienrb/build-grpc
I had to apply various patches to succeed...

Note that gRPC version 1.0.0 is actually incorrect : it builds ok but it is unusable because some .c and .cpp files share the same names thus the same output object file (one of the two is lost during the build)!

**Comment by a-teammate** [comment]
https://github.com/inexor-game/conan-grpc.git

Disclaimer: 
Its tested for Desktop Linux and Windows for the shared=False setting and the unsecure grpc packages. We needed to get it working first, so it might be not 100% covered by testing.
If you encounter bugs or anything alike we'd be happy for pull requests and patches.

**Comment by Brunni** [comment]
gRPC/1.1.0-dev@a_teammate/stable is working on ubuntu.
But I several stuff was missing on conan.io and had to be build from sources: grcp, protobuf and openssl

Can I upload the build things?

``` arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++
    compiler.version=6.1
    os=Linux
```

**Comment by memsharded** [comment]
Hi @Brunni ,

You can't upload binaries under other user username/account to conan.io. What you can do is first copy to your own username with ``$ conan copy`` command, then upload. Right now it is not possible to directly contribute binaries to other users accounts in conan.io (like a PR), nor grant permissions. It can be done with the conan_server (permissions can be configured). It is likely that we will be improving these things in the mid term.

**Comment by Croydon** [comment]
This can be closed I guess.

**Comment by helmesjo** [comment]
What's the state on this? I'm seeing a few "personal" recipes, but nothing in the public-conan/conan-center repositories.

**Comment by helmesjo** [comment]
@Croydon @memsharded @solvingj

My best find is [this gRPC recipe](https://github.com/inexorgame/conan-grpc/tree/stable/1.9.1) which unfortunately is sorta falling behind ([1.12.0](https://github.com/grpc/grpc/releases) is the most recent release at time of writing).

Could it perhaps be proposed for addition to [bincrafters](https://github.com/bincrafters)? That would make it feel a lot more reliable (since recipes there have rather strong maintenance & quality guarantees).

**Comment by helmesjo** [comment]
Their recipes are definitely not always up-to-date, of course. However I do believe they've created a very nice & clean generic template that all recipes follow, which further simplifies & speeds up "update"-requests.

Sure, but conan-center would be a step further though (it's the "official" conan repository, right?). Instead, including it in [bincrafters repository](bincrafters/public-conan) would be a smaller but rather reasonable step, I believe. 

But really, the main thing is that I'm planning to use gRPC for professional use, and anything other than [conan-center](https://conan.bintray.com) or [bincrafters public-conan](https://api.bintray.com/conan/bincrafters/public-conan) is a big "no no" at my company.

Either way, thanks for any effort put into this!

**Comment by solvingj** [comment]
We'd be happy to have GRPC in Bincrafters and then submit it to conan-center from there, but indeed it's complicated and important enough that it would need a champion within Bincrafters committed to being a primary maintainer within the group.  Everyone on the team has been super busy, and @uilianries and @SSE4 and some others have been working really hard just to handle maintenance on existing stuff.  Lets see if anyone can find the time over the next two weeks.

**Comment by sourcedelica** [comment]
I’m pushing to use gRPC at work.  If that happens then I would be happy to be the primary maintainer of a recipe.  I did a first cut a while ago in conan-transit, and it is indeed a beast.

**Comment by helmesjo** [comment]
That would be greatly appreciated! @sourcedelica 

Should this issue perhaps be reopened?

**Comment by Croydon** [comment]
Update: I just released a recipe for 1.14.1 https://github.com/inexorgame/conan-grpc

and I'm also working towards getting upstream support: https://github.com/grpc/grpc/issues/15363#issuecomment-408198240

**Comment by uilianries** [comment]
@Croydon Awesome!

**Comment by Croydon** [comment]
Please re-open this until grpc is in conan-center with official support

This will give it more exposure and maybe more helping hands 😄

**Comment by TheStormN** [comment]
Hey all,

Is there any progress on this? I see that the last blockers protobuf and protoc are already in conan-center-index. Is there anything else that needs to be done in order to get this package upstream? I can help if, help is needed.

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/3990 & https://github.com/conan-io/conan-center-index/pull/5364
