### ISSUE TITLE
zlib-ng

### ISSUE THREAD

**Issue by nathanaeljones** [conan-io/wishlist#6]
zlib-ng is a faster drop-in replacement for zlib. Development has remained very active for years.

https://github.com/Dead2/zlib-ng
Outdated benchmarks: https://www.snellman.net/blog/archive/2015-06-05-updated-zlib-benchmarks/

**Comment by lasote** [comment]
https://www.conan.io/source/zlib-ng/1.2.8/lasote/stable is not valid?

**Comment by nathanaeljones** [comment]
Sorry! Missed that! I assumed it didn't exist since we weren't already using it in Imageflow.
