### ISSUE TITLE
libusb/1.0.21

### ISSUE THREAD

**Issue by uilianries** [conan-io/wishlist#60]
**What?**
A cross-platform user library to access USB devices.

[libusb official site](http://libusb.info/)
[libusb project repository](https://github.com/libusb/libusb)

Supported OS: Linux, OS X, Windows, Windows CE, Android, OpenBSD/NetBSD, Haiku.

**Why?**
Projects that uses USB technology, since version 1.0 to 3.1, has a good opportunity to use the API for all platforms. 

**How?**
I believe that is very possible build in Linux, OS X, Windows, by default.

**Comment by impsnldavid** [comment]
+1

**Comment by uilianries** [comment]
You could check here: https://github.com/uilianries/conan-libusb  

However, I could not able to link with Windows dll (I can generate, but the linker fails when try to find the library), but static is working fine. Linux and Mac are working for all configurations.

**Comment by uilianries** [comment]
My last version at [Bintray](https://bintray.com/uilianries/conan/libusb%3Auilianries) is stable. It's working on all platforms (Linux/Mac/Windows).

**Comment by danimtb** [comment]
Already in conan center: https://bintray.com/bincrafters/public-conan/libusb%3Abincrafters

Thanks a lot @uilianries!!
