### ISSUE TITLE
New version of rapidjson/1.0.2-1/lasote/vcpkg

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/wishlist#63]
There already is a package for rapidjson 1.0.2 here:

https://www.conan.io/source/rapidjson/1.0.2-1/lasote/vcpkg

However, I would like to have version 1.1.0 available. 

I didn't find the conanfile in the repository linked at that page, however the conanfile.py is available on that page itself.

Can I just put the conanfile.py in a new repo and update the package version reference(s) to make the newer version available?

How can the package then be made available via conan.io repository?

Best regards

**Comment by lasote** [comment]
Hi, the vcpkg recipes are automatically generated using the "conanizer" folder of my vcpkg project fork (https://github.com/lasote/vcpkg)  that iterates every port and "transform" the port in a conan recipe.
If you want to know more about it we wrote a blog post: http://blog.conan.io/2016/10/17/Using-Vcpkg-ports-as-Conan-packages.html

I've updated my fork to get the latest ports (including rapidjson 1.1.0) and an appveyor build is currently working. https://ci.appveyor.com/project/lasote/vcpkg
If all goes well in some hours the rapidjson packages will be upgraded in conan.io.
Let me know if something goes wrong.

**Comment by CodingSpiderFox** [comment]
Thanks, I will try it when I have time.

**Comment by Brunni** [comment]
Hi, afaik RapidJson is a header only library. So building this correctly without vcpkg would make sense. We could just copy https://www.conan.io/source/RapidJSON/1.0.2/SamuelMarks/stable and change the version number.

**Comment by lasote** [comment]
@Brunni yes, you can copy the recipe to your user/channel and maintain the library without vcpkg

**Comment by Brunni** [comment]
I have upload one:
https://www.conan.io/source/RapidJSON/1.1.0/Brunni/stable

Had to amend some stuff so I forked it. I hope it works fine.

**Comment by CodingSpiderFox** [comment]
I ended up with using the package rapidjson/1.1.0@lasote/vcpkg and it worked well
