### ISSUE TITLE
Added library Apache Xerces-c for XML parsing

### ISSUE THREAD

**Issue by Brunni** [conan-io/wishlist#64]
Hi,

I just added a working Apache Xerces-C as the other did not build correctly.

conan: https://www.conan.io/source/xerces-c/3.1.4/Brunni/testing
build manual: https://xerces.apache.org/xerces-c/build-3.html
github: https://github.com/Brunni/conan-xerces-c

If anyone is interested in testing/reviewing this :)

**Comment by SSE4** [comment]
xerces-c is already in conan center
