### ISSUE TITLE
crow

### ISSUE THREAD

**Issue by SamuelMarks** [conan-io/wishlist#7]
> [**crow**](https://github.com/ipkn/crow) is a very fast and easy to use C++ micro web framework (inspired by Python's [Flask](http://flask.pocoo.org/))

Requirements (from [CMakeLists.txt](https://github.com/ipkn/crow/blob/686e5e220b782ef47b5c59271a946bd9603de1d1/CMakeLists.txt)):
- Boost (static, 1.52)
- [sqlpp11](https://github.com/rbock/sqlpp11) (optional)

PS: I've started experimenting with it, and am considering preparing a PR that'll bump the boost version

**Comment by memsharded** [comment]
You mean, have you started trying to make a conan package for it, or that you are experimenting with crow, and that you might submit a PR to the crow repo, so the Boost dependency is upgraded to a more modern one.

Also, would you need sqlpp11 for your use case? Even if it is optional for crow, if you plan to use it, it might worth having its own issue.

**Comment by SamuelMarks** [comment]
Haven't started on its conan package yet, just started code-reviewing on the boost dependency side.

Found an old issue that tried to remove the boost dependency entirely, so I'm keeping that in the back of my head as I review.

Hmm, good point about sqlpp11, might as well add another issue for it

**Comment by hoxnox** [comment]
https://bintray.com/hoxnox/conan/crow%3Ahoxnox
https://github.com/hoxnox/conan-crow

**Comment by Croydon** [comment]
@hoxnox Can you please add a LICENSE file with a license for your recipe (not the packages library)?

**Comment by Croydon** [comment]
Can be closed in favour of https://github.com/conan-io/conan-center-index/issues/3064

**Comment by SamuelMarks** [comment]
@Croydon Aww but was keen on my 4 year old issue being resolved 😝

**Comment by Croydon** [comment]
@SamuelMarks It is work in progress now, have a look here: https://github.com/conan-io/conan-center-index/pull/3123

**Comment by SamuelMarks** [comment]
Yeah I know, just not sure why this #3064 wasn't closed in favour of this old issue of mine (considering crow itself hasn't been updated in as many years)

Doesn't matter anymore, seeing as the other issue has now been closed by the bot, thanks to the merge

**Comment by Croydon** [comment]
The wishlist here is deprecated. New package request should be made directly in the issue tracker of the Conan Center Index and if we get a request both here and in the Index, we are always closing in favour of the Index issue
