### ISSUE TITLE
SDL2_mixer

### ISSUE THREAD

**Issue by phobos2077** [conan-io/wishlist#71]
https://www.libsdl.org/projects/SDL_mixer/

There are already a couple of "unofficial" packages for that library, but none of them work under Ubuntu 16.04.

**Comment by meniku** [comment]
I would like that too, the packages are not working on OS X too

**Comment by Croydon** [comment]
@sixten-hilborn put some work into https://github.com/sixten-hilborn/conan-sdl2_mixer

**Comment by SSE4** [comment]
https://github.com/bincrafters/conan-sdl2_mixer

**Comment by Croydon** [comment]
Can be closed in favor of https://github.com/conan-io/conan-center-index/issues/9018
