### ISSUE TITLE
template engine

### ISSUE THREAD

**Issue by qiukeren** [conan-io/wishlist#73]
Here is some suggest:

mustache

http://mustache.github.io/

ctemplate

https://github.com/OlafvdSpek/ctemplate

**Comment by cjalmeida** [comment]
Hi. I just added https://www.conan.io/source/CTemplate/2.3/cjalmeida/master

It might be of interest. If you see any bugs, please report at the package GitHub issues.

**Comment by qiukeren** [comment]
LGTM

best wishes
