### ISSUE TITLE
Stable boost 1.64 (CI build)

### ISSUE THREAD

**Issue by Brunni** [conan-io/wishlist#78]
Hi,
can somebody upgrade the version of the 1.60 boost version `Boost/1.60.0@lasote/stable`
https://github.com/lasote/conan-boost

I would need the version 1.64 and I cannot find one, where all packages are built (by CI).

Perhaps @lasote can update this :)

**Comment by lasote** [comment]
Yep, can be done, A thing that will be very very useful is to know which (not header only) libraries has been added (or removed) since 1.62.0. Could you take a look?

**Comment by Croydon** [comment]
https://github.com/inexor-game/conan-boost/commits/testing/1.64.0

We are kinda doing that already. We also plan to create a PR for lasote's repository, once we are sure it works fine.
We still have problems with Visual Studio 2017 right now.

I'm also not sure if somebody updated the libraries section. Help welcome :)

**Comment by Croydon** [comment]
I'm pretty confident that we are pull request ready.

@lasote Could you create a new branch release/1.64.0 based on the release/1.62.0 branch?

**Comment by lasote** [comment]
Done. I've deleted the CI scripts to prevent to upload 1.62 again.

**Comment by Brunni** [comment]
Hi, what is the current state? I'm really missing it :)

**Comment by Croydon** [comment]
Yeah, life and such..

Here you go :)
https://github.com/lasote/conan-boost/pull/47

**Comment by Croydon** [comment]
Merged. Can be closed.
