### ISSUE TITLE
Libtins/latest - network packet sniffing and crafting library

### ISSUE THREAD

**Issue by GuyKroizman** [conan-io/wishlist#79]
libtins is a high-level, multiplatform C++ network packet sniffing and crafting library. 

build doc:
`http://libtins.github.io/download/#requirements`
source at:
`git clone https://github.com/mfontanini/libtins.git`

For ubuntu 14.04 64 bit
without the optional WPA2 decryption so no need for the libcrypto - doc says to config with -DLIBTINS_ENABLE_WPA2=0
with c++11 enabled - doc says to config with -DLIBTINS_ENABLE_CXX11=1
I think I prefer static library but I did not see in the doc anything on how to achieve that.

**Comment by solvingJ** [comment]
I saw your post on the google group.  If I get around to making packages any time soon, I will try this one.

**Comment by solvingJ** [comment]
The current challenge with this is that libtins has a pretty rough set of dependencies: 
OpenSSL - Not a problem, already in Conan-Center
Boost - Not Yet Available in Conan-Center, apparently several weeks away at least
libpcap - Best candidate in Conan-Transit is a linux-only build.  Author is working on fixing MAC.  
libpcap transitive dependencies , none of which are in conan-center or even conan-transit - 
-   libpcap0.8-dev,libpcap-dev:i386 0.9
-   libubertooth-dev:i386,libpcap-dev:i386
-   libbtbb-dev:i386,libpcap-dev:i386
-   libbroccoli-dev:i386,libpcap-dev:i386
-   eclipse-titan:i386,libpcap-dev:i386
-   libpcap0.8-dev:i386,libpcap-dev:i386 0.9
-   libdpdk-dev:i386,libpcap-dev:i386

winpcap - Best candidate in Conan-Transit unlikely to be a candidate for adoption into Conan-Center.

**Comment by GuyKroizman** [comment]
Thanks @solvingJ. Do you (or anyone else listening) knows, if it is possible to have a something that is not perfect, like a package build for linux, that is built using the boost which is already on the system (apt-get/yum install and located using cmake find_library module).
This way we will have a base which will work for some people and maybe could gradually grow to be a complete solution in the future.

**Comment by solvingJ** [comment]
Thanks to @uilianries, I think we got there this weekend. I am working real hard to get it published today or tomorrow.

**Comment by solvingj** [comment]
@GuyKroizman It looks like I never posted the info here, but we've made a lot of improvements on the libtins package since July.  Here's the link, please let me know if it works for you. 

https://bintray.com/bincrafters/public-conan/libtins%3Abincrafters/3.5%3Astable

**Comment by Croydon** [comment]
Done by https://github.com/conan-io/conan-center-index/pull/4587
