### ISSUE TITLE
sqlpp11

### ISSUE THREAD

**Issue by SamuelMarks** [conan-io/wishlist#8]
> [**sqlpp11**](https://github.com/rbock/sqlpp11) is a type safe SQL template library for C++.

Requirements: (taken from [sqlpp11/README.md#requirements](https://github.com/rbock/sqlpp11/blob/e271e3e4fb86419c06dbe0d33dfc3aef2b23cc1a/README.md#requirements))

> **Compiler:**
> sqlpp11 makes heavy use of C++11 and requires a recent compiler and STL. The following compilers are known to compile the test programs:
> - clang-3.4+ on Ubuntu-12.4
> - g++-4.8+ on Ubuntu-12.4
> - g++-4.8+ on cygwin 64bit
> - g++-4.9+ on Debian Unstable
> - Xcode-7 on OS X
> - MSVC 2015 Update 1 on Windows Server 2012
> 
> **Database Connector:**
> sqlpp11 requires a certain api in order to connect with the database, see database/api.h.
> - MySQL: https://github.com/rbock/sqlpp11-connector-mysql
> - Sqlite3: https://github.com/rbock/sqlpp11-connector-sqlite3
> - PostgreSQL: https://github.com/matthijs/sqlpp11-connector-postgresql
> - ODBC: https://github.com/Erroneous1/sqlpp11-connector-odbc (experimental)
> 
> To demonstrate that sqlpp11 can work with other backends as well, here is an experimental backend for structs in standard containers:
> - STL Container: https://github.com/rbock/sqlpp11-connector-stl
> 
> **Date Library:**
> sqlpp11 requires [Howard Hinnant's date library](https://github.com/HowardHinnant/date) for `date` and `date_time` data types.

**Comment by memsharded** [comment]
I have created some packages:

- https://www.conan.io/source/sqlpp11-stl/0.4/memsharded/testing
- https://www.conan.io/source/sqlpp11/0.38/memsharded/testing
- https://www.conan.io/source/date/1.0.0/memsharded/testing

Date and Sqlpp11 are header only, test_package was able to work fine. Those packages seem OK.

The packages for the connectors, I have not been able to make them work. The STL one does not require external deps, but still fails while building a simple example, with compile errors in the example code, which is unexpected (package errors are mostly not found includes or linking errors).
I have tested both in Win (VS 2015 Upd2), Ubuntu gcc5.3

The package for the sqlite connector is still not finished, I have started it, without success so far.

I have used the latest tagged versions of everything, should be compatible between them? Could be reason?

Maybe you can try just the sqlpp11-stl connector, it requires the other two packages.

**Comment by DEGoodmanWilson** [comment]
I just gave a try at building a conanfile for the sqlite connector. It failed. The CMakeLists.txt is very…unusual. I am very interested in this library, so I would be interested in collaborating to help make this happen, @memsharded

**Comment by memsharded** [comment]
Ok, thanks for the input. My latest efforts were towards having a working MySQLClient, but then I got extremely busy, so this has been stalled for a while. You can also follow the conversation on https://github.com/rbock/sqlpp11/issues/103.

**Comment by rbock** [comment]
@DEGoodmanWilson Cleaning up some issues, I stumbled over this again. I'd be very glad if you or somebody else could help with the CMakeLists.txt. I freely admit that I am pretty much a cmake illiterate.

**Comment by Croydon** [comment]
WIP: https://github.com/bincrafters/conan-sqlpp11

**Comment by Croydon** [comment]
Done!

For tracking of the connectors I guess we do have #112 

https://github.com/conan-io/conan-center-index/pull/369

**Comment by danimtb** [comment]
That should be enough. Thanks @Croydon!
