### ISSUE TITLE
mongocxx/3.0 stable - driver for mongodb

### ISSUE THREAD

**Issue by GuyKroizman** [conan-io/wishlist#80]
mongocxx is a c++ driver for query, update data as well as perform administrative operations on a remote or local mongodb database.

source code:
`https://github.com/mongodb/mongo-cxx-driver/`

Installing the mongocxx driver:
`https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/installation/`

For: ubuntu 14.04   64 bit
as a static library
With MNMLSTC/core which is the default C++17 polyfill for non windows: -DBSONCXX_POLY_USE_MNMLSTC=1

**Comment by Socapex** [comment]
+1

**Comment by yannlabou** [comment]
+1

**Comment by yannlabou** [comment]
I would have been also fine with mongocxx/3.2 stable ;)

**Comment by promgamer** [comment]
I found out [this](https://github.com/DEGoodmanWilson/conan-mongo-c-driver), which needs some work on Windows stuff (if you feel like contributing!)

**Comment by Croydon** [comment]
https://github.com/bincrafters/community/issues/484

Ongoing work

**Comment by SSE4** [comment]
`mongo-c-driver` is available on bincrafters https://bintray.com/bincrafters/public-conan/mongo-c-driver:bincrafters
next is `mongo-cxx-driver`, stay in touch

**Comment by SSE4** [comment]
tracking on https://github.com/bincrafters/community/issues/485

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/3681
