### ISSUE TITLE
libjpeg-turbo

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [conan-io/wishlist#82]
https://github.com/libjpeg-turbo/libjpeg-turbo

Can we add this library?

**Comment by Croydon** [comment]
https://github.com/lasote/conan-libjpeg-turbo

**Comment by ZaMaZaN4iK** [comment]
When it will be available on conan-center?

**Comment by lasote** [comment]
There is no date. But you can clone the repository and use `conan create user/channel` to create your binaries and upload to your own personal open source Bintray repository until then.

**Comment by solvingj** [comment]
@ZaMaZaN4iK do you want to close this one now, or wait until we submit from bincrafters to conan-center?  Might be a month or two.

**Comment by ZaMaZaN4iK** [comment]
I think we can close it. Package is available on Bincrafters repo.

**Comment by danimtb** [comment]
Package already in conan-center. Recipe can be found here: https://github.com/bincrafters/conan-libjpeg-turbo
