### ISSUE TITLE
OpenEXR

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [conan-io/wishlist#86]
https://github.com/openexr/openexr/tree/develop/OpenEXR

**Comment by SSE4** [comment]
this one is dependency of OpenCV as well

**Comment by SSE4** [comment]
now available at conan-community https://github.com/conan-community/conan-openexr

**Comment by SSE4** [comment]
now in conan-center https://bintray.com/conan-community/conan/openexr%3Aconan
