### ISSUE TITLE
Google protobuf

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [conan-io/wishlist#87]
https://github.com/google/protobuf

**Comment by Croydon** [comment]
https://bintray.com/inexorgame/inexor-conan/Protobuf%3Ainexorgame

https://github.com/inexorgame/conan-protobuf

**Comment by ZaMaZaN4iK** [comment]
When it will be available on conan-center?

**Comment by Croydon** [comment]
We have currently no plans to apply our Protobuf Conan package for conan-center.

**Comment by SSE4** [comment]
there is new one in bincrafters repository: https://github.com/bincrafters/conan-protobuf

**Comment by ZaMaZaN4iK** [comment]
@SSE4 Is it proposed to conan-center?

**Comment by SSE4** [comment]
I hope this one will be reviewed and accepted soon

**Comment by SSE4** [comment]
Already in conan center
