### ISSUE TITLE
easyloggingpp

### ISSUE THREAD

**Issue by hoxnox** [conan-io/wishlist#9]
[easyloggingpp](https://github.com/easylogging/easyloggingpp#syslog) - popular one-header library for logging.

Requirements:

- version >8.91 - c++11
- version 8.91 - no requirements-

**Comment by memsharded** [comment]
Both versions uploaded to conan. The github repo is: https://github.com/memsharded/conan-easyloggingpp. Includes a basic test for each version.

They do not appear in the web, as one of the services we are using is broken, we are working on it. But they are usable, you can add them to your conanfile and it will work:

easyloggingpp/8.91@memsharded/testing
easyloggingpp/9.80@memsharded/testing

Uploading header-only packages is very easy, maybe you want to try next time, I can help if you want. Moreover, I have just submitted an issue that could automate further this process: https://github.com/conan-io/conan/issues/293

Please tell me if it worked.

Cheers!

**Comment by memsharded** [comment]
The web search is working again, now easylogging is discoverable in web search. Also added badges to the github repository.

**Comment by hoxnox** [comment]
Works great, thanks.

**Comment by memsharded** [comment]
Excellent thank you for telling! If some issue, update, etc... issues can be submitted to the repository of the package recipe itself: https://github.com/memsharded/conan-easyloggingpp
