### ISSUE TITLE
CGAL/4.11

### ISSUE THREAD

**Issue by acgetchell** [conan-io/wishlist#91]
Very important imaging library for scientific and other endeavors.

Requires Boost, Eigen, and best performance with TBB.

Best source is tagged releases on GitHub:

https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-4.11

OS: MacOS 10.13, Ubuntu Trusty, and Windows 10
Compilers: AppleClang 9.0.0, llvm, gcc, Visual Studio (14.0 needed, 15 nice)

**Comment by solvingj** [comment]
I found this one, let me see if we have someone who can refurbish it. 

https://github.com/barcharcraz/conan-packages/tree/develop/CGAL

**Comment by acgetchell** [comment]
Bump to CGAL 4.12

**Comment by Croydon** [comment]
CCI has now cgal 5.0. Is this okay for you? @acgetchell 

https://github.com/conan-io/conan-center-index/pull/622

**Comment by acgetchell** [comment]
Thanks for the work @Croydon !

I may check it out in a test project again sometime, but I switched to `vcpkg` last year as they had working ports of CGAL and TBB on Windows, Linux, and macOS.
