### ISSUE TITLE
GSL - GNU Scientific Library

### ISSUE THREAD

**Issue by zhitko** [conan-io/wishlist#94]
https://www.gnu.org/software/gsl/

The GNU Scientific Library (GSL) is a numerical library for C and C++ programmers. It is free software under the GNU General Public License.

Source code
git://git.savannah.gnu.org/gsl.git

**Comment by tkhyn** [comment]
I put together something that works here: https://bitbucket.org/tkhyn/conan-gsl

Has only been lightly tested on my platform (Win7x64 + TDM-gcc 64), so feel free to try it and report any issue over there.

**Comment by memsharded** [comment]
Thanks @tkhyn, very interesting. 
I am going to announce it in the conan channel (in CppLang slack team, if you'd like to join), to ask for feedback.

**Comment by ttbek** [comment]
This is still not in Conan-Center?  At least some people are still building workarounds for this: https://github.com/Chrismarsh/conan-gsl  Is there any reason it isn't there yet?

**Comment by Croydon** [comment]
> This is still not in Conan-Center? At least some people are still building workarounds for this: https://github.com/Chrismarsh/conan-gsl Is there any reason it isn't there yet?
 
This is not a "workaround". Conan Center is the official, central Conan repository, but everyone can create own repositories and create independently Conan recipes.

What is in Conan Center and what not really comes down to contributions. Every help is welcome! 😄

**Comment by rl-enjoyer** [comment]
How do you contribute to conan center?

**Comment by Croydon** [comment]
@NolanC33 Have a look here: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md

**Comment by Croydon** [comment]
Can be closed in favor of https://github.com/conan-io/conan-center-index/issues/6097
