### ISSUE TITLE
Armadillo: C++ linear algebra library

### ISSUE THREAD

**Issue by liebkne** [conan-io/wishlist#96]
> Armadillo is a high quality linear algebra library (matrix maths) for the C++ language, aiming towards a good balance between speed and ease of use.

Home: http://arma.sourceforge.net
Repo: https://github.com/conradsnicta/armadillo-code/

My working platform is `macOS 10.12.6` with `cmake version 3.10.0` and `clang 5.0.0`. I choose this package because its much more friendly interface compared to `Eigen`. I came from the `bincrafters/community` repo. Thank you very much!

**Comment by memsharded** [comment]
Armadillo is there ready for review in conan-center, I think.
Also @danimtb is checking it. May be available soon.

**Comment by danimtb** [comment]
Armadillo package is not yet ready for admission in conan-center. Seems the package would need a refurbish: https://bintray.com/slidewavellc/conan-libs/Armadillo%3Aslidewave

However, there is also a new development package in an early stage but it is working and updated to latest conan: https://github.com/Yevgnen/conan-armadillo

It could be a good starting point to contribute to conan-center @isolet!

**Comment by Croydon** [comment]
Can be closed in favor of https://github.com/conan-io/conan-center-index/issues/6754
