### ISSUE TITLE
nghttp2/1.29.0

### ISSUE THREAD

**Issue by drrlvn** [conan-io/wishlist#98]
An HTTP/2.0 C library with a high level C++ API.

[1] https://nghttp2.org/
[2] https://nghttp2.org/documentation/libnghttp2_asio.html

**Comment by theirix** [comment]
Remind me: if it will be uploaded, it would be nice to have libcurl integrated with nghttp2

**Comment by theirix** [comment]
Done with 1.38.0 - https://github.com/bincrafters/conan-nghttp2 

libcurl integration is ongoing.

**Comment by theirix** [comment]
Added libcurl integration for version 7.64.1

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/173
