### ISSUE TITLE
c-ares

### ISSUE THREAD

**Issue by Croydon** [conan-io/wishlist#99]
https://github.com/c-ares/c-ares

I have found this: https://github.com/lhcorralo/conan-c-ares
According to the author it works only under Windows, it also needs updates for newer Conan versions and should get support for Linux + macOS

@lhcorralo put it under MIT license so somebody can take it over

**Comment by lhcorralo** [comment]
@Croydon, I think it is already under the MIT license (see https://github.com/lhcorralo/conan-c-ares/blob/master/LICENSE). I do not know if it is enough... If not, I cannot change it at the moment (I do not have any proper pc at the moment), but feel free to use, copy or modify it.

**Comment by Croydon** [comment]
@lhcorralo Yes, it is under MIT license. That's what I said. Sorry, if there was confusion :)

**Comment by Croydon** [comment]
I have played with it a bit https://github.com/Croydon/conan-c-ares

  * it works now with Conan >= 1.0.0
  * updated to c-ares 1.13.0
  * added some basic CI
  * uses CMake on Linux & macOS now
  * "almost" works under Linux and macOS now
    * it seems to build fine, but it doesn't export the libs for some reason
  * Windows builds and exports successfully but has a problem with the test package 
     * Visual Studio 2017 doesn't work yet but this is a limitation in c-ares itself and gets solves with the next update

**Comment by Croydon** [comment]
Update:
  * I have switched Windows to CMake as well
    * this added VS 2017 support 
  * I have removed the test_package for now as it is way to broken
    * maybe the official c-ares tests from their repository could be used, but this might be tricky, since AFAIK you need to build them with c-ares and can't add/execute them later. Building c-ares seperately for tests kinda defeats the purpose.
  * lib exporting should work now for all configurations
  * the findcares.cmake script is still broken

**Comment by lasote** [comment]
Hi @Croydon! I have this recipe, currently working on Mac and Linux prefectly, but the example in my test package is not able to contact the DNSs in Windows, could you take a look? I don't know if the example is written ok or if there is something wrong with the built library.
As you have a c-ares recipe working in windows, Could you run some test (example, project...) against my library and report?

This is the remote with some packages uploaded:
`https://api.bintray.com/conan/conan-community/conan`

This is the reference:

`c-ares/1.14.0@conan/stable`

This is the repo:
https://github.com/conan-community/conan-c-ares

**Comment by Croydon** [comment]
@lasote Your message didn't catch my attention, sorry! I just noticed via Twitter that c-ares is now in conan-center so I revisited this issue.

I'm using c-ares as a depencency for grpc, but not directly. Does the c-ares test packages still need some testing on Windows?

**Comment by lasote** [comment]
No! They are fixed now. It was required to initialize winsocks in the consumer. So it should be ok!
